import type { CatalogEntry, ConnectorActionPolicy, Transport } from './types';
import { RAKUTEN_ICON, COLORME_ICON, BASE_ICON, QOO10_ICON, FUTURESHOP_ICON, YAHOO_SHOPPING_ICON } from './catalog-japan-brand-icons';
import { LOCAL_API_REDIRECT_URI } from './oauth-redirect';

const CALLBACK_HELP = {
  callback_help_zh: '将此完整地址登记到开发者应用的回调地址设置中，需与授权时使用的地址一致。',
  callback_help_en: 'Register this exact URL as the developer app’s callback; it must match the URL used for authorization.',
  callback_help_es: "Registra esta URL exacta como URL de retorno de la aplicación de desarrollador; debe coincidir con la URL usada para la autorización.",
  callback_help_fr: "Enregistrez cette URL exacte comme URL de rappel de l’application développeur ; elle doit correspondre à l’URL utilisée pour l’autorisation.",
  callback_help_ko: "이 URL을 그대로 개발자 앱의 콜백으로 등록하세요. 승인에 사용하는 URL과 일치해야 합니다.",
  callback_help_de: "Registrieren Sie genau diese URL als Callback der Entwickler-App; sie muss mit der für die Autorisierung verwendeten URL übereinstimmen.",
  callback_help_ru: "Зарегистрируйте именно этот URL как обратный вызов приложения разработчика; он должен совпадать с URL, используемым при авторизации.",
  callback_help_it: "Registra esattamente questo URL come callback dell'app sviluppatore; deve corrispondere all'URL usato per l'autorizzazione.",
  callback_help_ja: 'この URL を開発者アプリのコールバックに完全一致で登録してください。認可時の URL と一致する必要があります。',
  callback_help_pt: 'Registre esta URL exata como callback do app; ela deve corresponder à URL usada na autorização.',
};

function applicationCredentialHelp(platform: string, key: string) {
  const label = key === 'client_id' ? 'Client ID' : 'Client Secret';
  return {
    help_zh: `从已获批的 ${platform} 应用凭据页复制 ${label}；此处不填写店铺登录密码。`,
    help_en: `Copy ${label} from the approved ${platform} app’s credentials page. This is not your shop login password.`,
    help_es: "Copia " + label + " de la página de credenciales de la aplicación aprobada de " + platform + ". No es la contraseña de inicio de sesión de tu tienda.",
    help_fr: "Copiez " + label + " depuis la page des identifiants de l’application " + platform + " approuvée. Il ne s’agit pas du mot de passe de connexion de votre boutique.",
    help_ko: "승인된 " + platform + " 앱의 자격 증명 페이지에서 " + label + " 값을 복사하세요. 상점 로그인 비밀번호가 아닙니다.",
    help_de: "Kopieren Sie " + label + " von der Zugangsdaten-Seite der genehmigten " + platform + "-App. Dies ist nicht Ihr Shop-Anmeldepasswort.",
    help_ru: "Скопируйте " + label + " со страницы учётных данных одобренного приложения " + platform + ". Это не пароль для входа в магазин.",
    help_it: "Copia " + label + " dalla pagina delle credenziali dell’app " + platform + " approvata. Non è la password di accesso al tuo negozio.",
    help_ja: `承認済み ${platform} アプリの認証情報ページから ${label} をコピーします。店舗ログインのパスワードではありません。`,
    help_pt: `Copie ${label} da página de credenciais do app ${platform} aprovado. Não é a senha de login da loja.`,
  };
}

// Reviewed against the official tools.json on 2026-09-16. Upstream additions
// remain hidden until reviewed here; annotations cannot downgrade these policies.
const read = ['getShop', 'getSales', 'statSale', 'getSale', 'getProducts', 'getProduct',
  'getProductVariants', 'getProductImages', 'getStocks', 'getReviews',
  'getProductGroups', 'getProductGroup', 'getProductCategories', 'getCoupons', 'getCoupon'];
const policies: Record<string, ConnectorActionPolicy> = Object.fromEntries(
  read.map(name => [name, { risk: 'R', confirmation: 'none', max_batch_size: 100 }]),
);
for (const name of ['postProducts', 'updateProduct', 'updateSale', 'createCoupon', 'updateCoupon', 'createPaymentUrls']) {
  policies[name] = { risk: 'H', confirmation: 'fresh', sensitive_operation: 'money', max_batch_size: 1 };
}
policies.sendSalesMail = { risk: 'H', confirmation: 'fresh', sensitive_operation: 'external_communication', max_batch_size: 1 };
policies.cancelSale = { risk: 'D', confirmation: 'destructive', sensitive_operation: 'money', max_batch_size: 1 };
policies.deleteCoupon = { risk: 'D', confirmation: 'destructive', sensitive_operation: 'delete', max_batch_size: 1 };

export const JAPAN_COMMERCE_ENTRIES: CatalogEntry[] = [{
  id: 'colorme-shop', display_name: 'Color Me Shop', category: 'commerce',
  icon_svg: COLORME_ICON.svg, icon_source_url: COLORME_ICON.source_url, icon_source_sha256: COLORME_ICON.source_sha256,
  description_zh: '通过免费官方连接管理商品、库存、订单和优惠券。请先在店铺应用商店安装「カラーミーショップ AIコネクター」，再登录授权。',
  description_en: 'Manage products, stock, orders and coupons through the free official connector. First install Color Me Shop AI Connector from your shop’s app store, then sign in to authorize.',
  description_es: "Gestiona productos, existencias, pedidos y cupones mediante el conector oficial gratuito. Primero instala Color Me Shop AI Connector desde la tienda de aplicaciones de tu tienda y después inicia sesión para autorizar.",
  description_fr: "Gérez les produits, les stocks, les commandes et les coupons via le connecteur officiel gratuit. Installez d’abord Color Me Shop AI Connector depuis la boutique d’applications de votre boutique, puis connectez-vous pour autoriser l’accès.",
  description_ko: "무료 공식 커넥터로 상품, 재고, 주문, 쿠폰을 관리합니다. 먼저 상점의 앱 스토어에서 Color Me Shop AI Connector를 설치한 후 로그인하여 승인하세요.",
  description_de: "Verwalten Sie Produkte, Bestände, Bestellungen und Gutscheine über den kostenlosen offiziellen Konnektor. Installieren Sie zuerst Color Me Shop AI Connector aus dem App-Store Ihres Shops und melden Sie sich dann zur Autorisierung an.",
  description_ru: "Управляйте товарами, запасами, заказами и купонами через бесплатный официальный коннектор. Сначала установите Color Me Shop AI Connector из магазина приложений вашего магазина, затем войдите для авторизации.",
  description_it: "Gestisci prodotti, scorte, ordini e coupon tramite il connettore ufficiale gratuito. Installa prima Color Me Shop AI Connector dallo store delle app del tuo negozio, quindi accedi per autorizzare.",
  description_ja: '無料の公式接続で商品・在庫・受注・クーポンを管理します。先にアプリストアで「カラーミーショップ AIコネクター」をインストールし、ログインして認可してください。',
  description_pt: 'Gerencie produtos, estoque, pedidos e cupons pelo conector oficial gratuito. Primeiro instale Color Me Shop AI Connector na loja de apps e entre para autorizar.',
  auth_mode: 'mcp_dcr',
  setup_guide_id: 'colorme-shop',
  connection_setup: {
    requirement: 'provider_application', fields: [],
    guide_url: 'https://app.shop-pro.jp/apps/956',
    guide_label_zh: '打开官方 AI 连接器应用', guide_label_en: 'Open the official AI Connector app',
    guide_label_es: "Abrir la aplicación oficial AI Connector",
    guide_label_fr: "Ouvrir l’application officielle AI Connector",
    guide_label_ko: "공식 AI Connector 앱 열기",
    guide_label_de: "Offizielle AI Connector-App öffnen",
    guide_label_ru: "Открыть официальное приложение AI Connector",
    guide_label_it: "Apri l'app ufficiale AI Connector",
    guide_label_ja: '公式 AI コネクターアプリを開く', guide_label_pt: 'Abrir o app oficial AI Connector',
    instructions_zh: '先在目标店铺安装免费的「カラーミーショップ AIコネクター」。安装完成后点击连接，在官方页面登录并授权；无需自行创建开发者应用或填写密钥。',
    instructions_en: 'Install the free Color Me Shop AI Connector in the intended shop first. Then connect and sign in on the official authorization page. No developer app or manually entered key is needed.',
    instructions_es: "Instala primero la aplicación gratuita Color Me Shop AI Connector en la tienda que quieras conectar. Después conecta e inicia sesión en la página oficial de autorización. No se necesita una aplicación de desarrollador ni introducir una clave manualmente.",
    instructions_fr: "Installez d’abord le connecteur gratuit Color Me Shop AI Connector dans la boutique voulue. Connectez ensuite le connecteur et identifiez-vous sur la page d’autorisation officielle. Aucune application développeur ni clé saisie manuellement n’est nécessaire.",
    instructions_ko: "먼저 연결할 상점에 무료 Color Me Shop AI Connector를 설치하세요. 그런 다음 연결하고 공식 승인 페이지에서 로그인하세요. 개발자 앱이나 수동으로 입력하는 키는 필요하지 않습니다.",
    instructions_de: "Installieren Sie zuerst den kostenlosen Color Me Shop AI Connector im gewünschten Shop. Stellen Sie dann die Verbindung her und melden Sie sich auf der offiziellen Autorisierungsseite an. Eine Entwickler-App oder manuell eingegebene Schlüssel sind nicht erforderlich.",
    instructions_ru: "Сначала установите бесплатный Color Me Shop AI Connector в нужном магазине. Затем подключитесь и войдите на официальной странице авторизации. Приложение разработчика и ввод ключа вручную не нужны.",
    instructions_it: "Installa prima Color Me Shop AI Connector, gratuito, nel negozio desiderato. Quindi collegati e accedi nella pagina ufficiale di autorizzazione. Non servono un'app sviluppatore né una chiave inserita manualmente.",
    instructions_ja: '対象ショップに無料の「カラーミーショップ AIコネクター」を先にインストールします。その後、接続を押して公式画面でログイン・認可します。開発者アプリの作成やキーの入力は不要です。',
    instructions_pt: 'Instale primeiro o app gratuito Color Me Shop AI Connector na loja desejada. Depois conecte e entre na página oficial de autorização. Não é preciso criar app de desenvolvedor nem informar chaves.',
  },
  required_oauth_scopes: ['openid', 'read_products', 'read_sales', 'read_shop_coupons',
    'write_products', 'write_sales', 'write_shop_coupons', 'offline_access'],
  allowed_tools: Object.keys(policies), tool_policies: policies,
  transport_template: { kind: 'streamable-http', url: 'https://agent.colorme.app/api/mcp', oauth_header_key: 'Authorization' },
}];

export function japanMerchantEntries(toolPolicies: Record<string, ConnectorActionPolicy>, transport: Transport): CatalogEntry[] {
  const tools = ['list_capabilities', 'describe_action', 'execute_read', 'execute_high_impact'];
  return [{
    id: 'rakuten-rms', display_name: 'Rakuten RMS', display_name_en: 'Rakuten RMS', display_name_zh: '乐天 RMS', category: 'commerce',
    auth_mode: 'local_api', local_api: { provider: 'rakuten_rms' }, setup_guide_id: 'rakuten-rms',
    icon_svg: RAKUTEN_ICON.svg, icon_source_url: RAKUTEN_ICON.source_url, icon_source_sha256: RAKUTEN_ICON.source_sha256,
    description_zh: '使用商家 RMS API 凭据读取商品、SKU 库存和订单摘要，按操作权限修改库存。商家需开通相应 API；无需创建 Orkas 开发者应用。',
    description_en: 'Use merchant RMS API credentials to read products, SKU stock and order summaries, and update stock under your operation permissions. Enable the required shop APIs; no Orkas developer app is needed.',
    description_es: "Usa las credenciales de la API RMS del comerciante para leer productos, existencias por SKU y resúmenes de pedidos, y actualizar existencias según tus permisos de operación. Habilita las API de tienda necesarias; no se necesita una aplicación de desarrollador de Orkas.",
    description_fr: "Utilisez les identifiants API RMS du marchand pour consulter les produits, les stocks par SKU et les résumés de commandes, et mettre à jour les stocks selon vos autorisations d’opération. Activez les API de boutique requises ; aucune application développeur Orkas n’est nécessaire.",
    description_ko: "판매자 RMS API 자격 증명으로 상품, SKU 재고, 주문 요약을 읽고 보유한 작업 권한 내에서 재고를 업데이트합니다. 필요한 상점 API를 활성화하세요. Orkas 개발자 앱은 필요하지 않습니다.",
    description_de: "Verwenden Sie die RMS-API-Zugangsdaten des Händlers, um Produkte, SKU-Bestände und Bestellübersichten zu lesen und Bestände gemäß Ihren Vorgangsberechtigungen zu aktualisieren. Aktivieren Sie die erforderlichen Shop-APIs; eine Orkas-Entwickler-App ist nicht erforderlich.",
    description_ru: "Используйте учётные данные RMS API продавца для чтения товаров, запасов SKU и сводок заказов, а также обновления запасов в пределах ваших разрешений на операции. Включите необходимые API магазина; приложение разработчика Orkas не требуется.",
    description_it: "Usa le credenziali RMS API del commerciante per leggere prodotti, scorte per SKU e riepiloghi degli ordini e aggiornare le scorte in base alle tue autorizzazioni operative. Abilita le API del negozio necessarie; non serve un'app sviluppatore Orkas.",
    description_ja: '店舗の RMS API 認証情報で商品・SKU 在庫・注文概要を取得し、操作権限に従って在庫を更新します。必要な店舗 API を有効にしてください。Orkas の開発者アプリは不要です。',
    description_pt: 'Use credenciais da API RMS da loja para consultar produtos, estoque por SKU e resumos de pedidos e atualizar estoque conforme suas permissões. Ative as APIs necessárias; não exige app de desenvolvedor Orkas.',
    allowed_tools: tools, tool_policies: Object.fromEntries(tools.map(name => [name, toolPolicies[name]])), transport_template: transport,
    connection_setup: {
      requirement: 'provider_application',
      guide_url: 'https://webservice.rms.rakuten.co.jp/',
      guide_label_zh: '打开 RMS 官方 API 文档', guide_label_en: 'Open the official RMS API documentation',
      guide_label_es: "Abrir la documentación oficial de la API RMS",
      guide_label_fr: "Ouvrir la documentation officielle de l’API RMS",
      guide_label_ko: "공식 RMS API 문서 열기",
      guide_label_de: "Offizielle RMS-API-Dokumentation öffnen",
      guide_label_ru: "Открыть официальную документацию RMS API",
      guide_label_it: "Apri la documentazione ufficiale delle RMS API",
      guide_label_ja: 'RMS 公式 API ドキュメントを開く', guide_label_pt: 'Abrir a documentação oficial da API RMS',
      instructions_zh: '在目标店铺 RMS 的 WEB API 服务中开通 Item API 2.0、Inventory API 2.1 和楽天ペイ受注 API 的对应操作。将 serviceSecret 与 licenseKey 填入下方保护字段。连接时仅验证商品读取权限；库存与订单权限在使用时分别检查。密钥过期或轮换后需重新配置。',
      instructions_en: 'In the intended shop’s RMS WEB API service, enable the corresponding Item API 2.0, Inventory API 2.1 and Rakuten Pay Order API operations. Enter serviceSecret and licenseKey below. Connecting verifies product-read access only; stock and order permissions are checked when used. Reconfigure expired or rotated keys.',
      instructions_es: "En el servicio RMS WEB API de la tienda que quieras conectar, habilita las operaciones correspondientes de Item API 2.0, Inventory API 2.1 y Rakuten Pay Order API. Introduce serviceSecret y licenseKey a continuación. La conexión solo verifica el acceso de lectura de productos; los permisos de existencias y pedidos se comprueban cuando se usan. Vuelve a configurar las claves caducadas o rotadas.",
      instructions_fr: "Dans le service RMS WEB API de la boutique voulue, activez les opérations correspondantes Item API 2.0, Inventory API 2.1 et Rakuten Pay Order API. Saisissez serviceSecret et licenseKey ci-dessous. La connexion vérifie uniquement l’accès en lecture aux produits ; les autorisations de stocks et de commandes sont vérifiées lors de leur utilisation. Reconfigurez les clés expirées ou renouvelées.",
      instructions_ko: "연결할 상점의 RMS WEB API 서비스에서 해당 Item API 2.0, Inventory API 2.1, Rakuten Pay Order API 작업을 활성화하세요. 아래에 serviceSecret과 licenseKey를 입력하세요. 연결 시에는 상품 읽기 권한만 확인하며, 재고 및 주문 권한은 사용 시 확인합니다. 키가 만료되거나 교체되면 다시 설정하세요.",
      instructions_de: "Aktivieren Sie im RMS WEB API-Dienst des gewünschten Shops die entsprechenden Vorgänge von Item API 2.0, Inventory API 2.1 und Rakuten Pay Order API. Geben Sie unten serviceSecret und licenseKey ein. Beim Verbinden wird nur der Lesezugriff auf Produkte geprüft; Bestands- und Bestellberechtigungen werden bei Verwendung geprüft. Konfigurieren Sie abgelaufene oder ausgetauschte Schlüssel neu.",
      instructions_ru: "В сервисе RMS WEB API нужного магазина включите соответствующие операции Item API 2.0, Inventory API 2.1 и Rakuten Pay Order API. Введите serviceSecret и licenseKey ниже. При подключении проверяется только доступ на чтение товаров; разрешения для запасов и заказов проверяются при использовании. При истечении срока или смене ключей настройте их заново.",
      instructions_it: "Nel servizio RMS WEB API del negozio desiderato, abilita le operazioni corrispondenti di Item API 2.0, Inventory API 2.1 e Rakuten Pay Order API. Inserisci serviceSecret e licenseKey qui sotto. La connessione verifica solo l'accesso in lettura ai prodotti; le autorizzazioni per scorte e ordini vengono verificate al momento dell'uso. Riconfigura le chiavi scadute o sostituite.",
      instructions_ja: '対象店舗の RMS WEB API サービスで Item API 2.0、Inventory API 2.1、楽天ペイ受注 API の対象機能を有効にします。serviceSecret と licenseKey を下記に入力します。接続時は商品の参照権限のみ確認し、在庫・注文の権限は利用時に確認します。期限切れ・更新後は再設定が必要です。',
      instructions_pt: 'No serviço WEB API do RMS da loja desejada, ative as operações de Item API 2.0, Inventory API 2.1 e Rakuten Pay Order API. Informe serviceSecret e licenseKey abaixo. A conexão verifica apenas leitura de produtos; permissões de estoque e pedidos são verificadas ao usar. Reconfigure chaves expiradas ou substituídas.',
      fields: (['service_secret', 'license_key'] as const).map(key => ({
        key, input: 'secret' as const, storage: 'credential' as const, format: 'secret' as const, required: true,
        label_zh: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
        label_en: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_es: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_fr: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_ko: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_de: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_ru: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
    label_it: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
        label_ja: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
        label_pt: key === 'service_secret' ? 'serviceSecret' : 'licenseKey',
        help_zh: '从目标店铺的 RMS WEB API 服务复制原始值，不填登录密码、Affiliate Application ID 或 Base64 编码结果。',
        help_en: 'Copy the original value from the intended shop’s RMS WEB API service, not a login password, affiliate Application ID or Base64-encoded value.',
        help_es: "Copia el valor original del servicio RMS WEB API de la tienda que quieras conectar, no una contraseña de inicio de sesión, un Application ID de afiliado ni un valor codificado en Base64.",
        help_fr: "Copiez la valeur d’origine depuis le service RMS WEB API de la boutique voulue, et non un mot de passe de connexion, un Application ID d’affiliation ou une valeur encodée en Base64.",
        help_ko: "연결할 상점의 RMS WEB API 서비스에서 원본 값을 복사하세요. 로그인 비밀번호, 제휴 Application ID, Base64로 인코딩된 값은 사용하지 마세요.",
        help_de: "Kopieren Sie den ursprünglichen Wert aus dem RMS WEB API-Dienst des gewünschten Shops, kein Anmeldepasswort, keine Affiliate-Application ID und keinen Base64-codierten Wert.",
        help_ru: "Скопируйте исходное значение из сервиса RMS WEB API нужного магазина, а не пароль для входа, партнёрский Application ID или значение в кодировке Base64.",
        help_it: "Copia il valore originale dal servizio RMS WEB API del negozio desiderato, non una password di accesso, un Application ID di affiliazione o un valore codificato in Base64.",
        help_ja: '対象店舗の RMS WEB API サービスから元の値をコピーします。ログインパスワード、アフィリエイト Application ID、Base64 変換後の値ではありません。',
        help_pt: 'Copie o valor original do serviço WEB API do RMS da loja desejada, não a senha de login, Application ID de afiliado nem um valor codificado em Base64.',
      })),
    },
  }, {
    id: 'base-shop', display_name: 'BASE', category: 'commerce', auth_mode: 'local_api', local_api: { provider: 'base_shop' },
    setup_guide_id: 'base-shop',
    icon_svg: BASE_ICON.svg, icon_source_url: BASE_ICON.source_url, icon_source_sha256: BASE_ICON.source_sha256,
    description_zh: '连接日本 BASE 店铺，读取商品、订单及库存，确认后修改商品或规格库存。需要已获批的 BASE 开发者应用。',
    description_en: 'Connect a Japanese BASE shop to read products, orders and stock, and update item or variation stock with confirmation. Requires an approved BASE developer app.',
    description_es: "Conecta una tienda japonesa de BASE para leer productos, pedidos y existencias, y actualizar las existencias de artículos o variantes con confirmación. Requiere una aplicación de desarrollador de BASE aprobada.",
    description_fr: "Connectez une boutique BASE japonaise pour consulter les produits, les commandes et les stocks, et mettre à jour les stocks d’articles ou de variantes avec confirmation. Nécessite une application développeur BASE approuvée.",
    description_ko: "일본 BASE 상점을 연결해 상품, 주문, 재고를 읽고 확인 후 상품 또는 옵션 재고를 업데이트합니다. 승인된 BASE 개발자 앱이 필요합니다.",
    description_de: "Verbinden Sie einen japanischen BASE-Shop, um Produkte, Bestellungen und Bestände zu lesen und Artikel- oder Variantenbestände mit Bestätigung zu aktualisieren. Erfordert eine genehmigte BASE-Entwickler-App.",
    description_ru: "Подключите японский магазин BASE для чтения товаров, заказов и запасов, а также обновления запасов товаров или вариантов с подтверждением. Нужно одобренное приложение разработчика BASE.",
    description_it: "Collega un negozio BASE giapponese per leggere prodotti, ordini e scorte e aggiornare le scorte di articoli o varianti previa conferma. Richiede un'app sviluppatore BASE approvata.",
    description_ja: 'BASE ショップの商品・注文・在庫を参照し、確認後に商品またはバリエーションの在庫を更新します。承認済み開発者アプリが必要です。',
    description_pt: 'Conecte uma loja japonesa BASE para consultar produtos, pedidos e estoque e alterar estoque de itens ou variações mediante confirmação. Exige app de desenvolvedor aprovado.',
    allowed_tools: tools, tool_policies: Object.fromEntries(tools.map(name => [name, toolPolicies[name]])), transport_template: transport,
    connection_setup: {
      requirement: 'provider_application', callback_url: LOCAL_API_REDIRECT_URI,
      ...CALLBACK_HELP,
      guide_url: 'https://docs.thebase.in/api/',
      guide_label_zh: '打开 BASE 官方开发者指南', guide_label_en: 'Open the official BASE developer guide',
      guide_label_es: "Abrir la guía oficial para desarrolladores de BASE",
      guide_label_fr: "Ouvrir le guide développeur officiel de BASE",
      guide_label_ko: "BASE 공식 개발자 가이드 열기",
      guide_label_de: "Offiziellen BASE-Entwicklerleitfaden öffnen",
      guide_label_ru: "Открыть официальное руководство разработчика BASE",
      guide_label_it: "Apri la guida ufficiale per sviluppatori BASE",
      guide_label_ja: 'BASE 公式開発者ガイドを開く', guide_label_pt: 'Abrir o guia oficial de desenvolvedores BASE',
      instructions_zh: '先申请 BASE API 应用并配置下方回调地址。填入该应用的 Client ID 和 Client Secret 后，在 BASE 官方页面登录目标店铺并授权。令牌会自动刷新；授权过期或被撤销时需重新连接。',
      instructions_en: 'Apply for BASE API access and register the callback below. Enter your app’s Client ID and Client Secret, then sign in to the intended shop on BASE to authorize. Tokens refresh automatically; reconnect if authorization expires or is revoked.',
      instructions_es: "Solicita acceso a la API de BASE y registra la URL de retorno que aparece a continuación. Introduce el Client ID y el Client Secret de tu aplicación y después inicia sesión en BASE con la tienda que quieras conectar para autorizar. Los tokens se actualizan automáticamente; vuelve a conectar si la autorización caduca o se revoca.",
      instructions_fr: "Demandez l’accès à l’API BASE et enregistrez l’URL de rappel ci-dessous. Saisissez les Client ID et Client Secret de votre application, puis connectez-vous à la boutique voulue sur BASE pour autoriser l’accès. Les jetons sont actualisés automatiquement ; reconnectez-vous si l’autorisation expire ou est révoquée.",
      instructions_ko: "BASE API 접근 권한을 신청하고 아래 콜백을 등록하세요. 앱의 Client ID와 Client Secret을 입력한 후 BASE에서 연결할 상점에 로그인하여 승인하세요. 토큰은 자동으로 갱신됩니다. 승인이 만료되거나 취소되면 다시 연결하세요.",
      instructions_de: "Beantragen Sie BASE-API-Zugriff und registrieren Sie den unten angegebenen Callback. Geben Sie Client ID und Client Secret Ihrer App ein und melden Sie sich dann beim gewünschten Shop auf BASE an, um den Zugriff zu autorisieren. Tokens werden automatisch erneuert; verbinden Sie den Shop erneut, wenn die Autorisierung abläuft oder widerrufen wird.",
      instructions_ru: "Подайте заявку на доступ к BASE API и зарегистрируйте обратный вызов ниже. Введите Client ID и Client Secret приложения, затем войдите в нужный магазин на BASE для авторизации. Токены обновляются автоматически; подключитесь заново, если авторизация истечёт или будет отозвана.",
      instructions_it: "Richiedi l'accesso alle API BASE e registra il callback qui sotto. Inserisci Client ID e Client Secret della tua app, quindi accedi al negozio desiderato su BASE per autorizzare. I token si aggiornano automaticamente; riconnettiti se l'autorizzazione scade o viene revocata.",
      instructions_ja: 'BASE API の利用申請を行い、下記コールバックを登録します。アプリの Client ID と Client Secret を入力し、BASE 公式画面で対象ショップにログインして認可します。トークンは自動更新されますが、認可の期限切れ・取消時は再接続が必要です。',
      instructions_pt: 'Solicite acesso à API BASE e registre o callback abaixo. Informe Client ID e Client Secret do app e entre na loja desejada na BASE para autorizar. Os tokens são renovados automaticamente; reconecte se a autorização expirar ou for revogada.',
      fields: ['client_id', 'client_secret'].map(key => ({ key, input: 'secret', storage: 'credential',
        ...applicationCredentialHelp('BASE', key),
        format: key === 'client_id' ? 'client_id' : 'secret', required: true,
        label_zh: key === 'client_id' ? 'Client ID' : 'Client Secret', label_en: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_es: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_fr: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ko: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_de: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ru: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_it: key === 'client_id' ? 'Client ID' : 'Client Secret',
        label_ja: key === 'client_id' ? 'Client ID' : 'Client Secret', label_pt: key === 'client_id' ? 'Client ID' : 'Client Secret',
      })),
    },
  }, {
    id: 'qoo10-japan', display_name: 'Qoo10 Japan', category: 'commerce', auth_mode: 'local_api', local_api: { provider: 'qoo10_japan' },
    setup_guide_id: 'qoo10-japan',
    icon_svg: QOO10_ICON.svg, icon_source_url: QOO10_ICON.source_url, icon_source_sha256: QOO10_ICON.source_sha256,
    description_zh: '使用商家认证密钥读取日本 Qoo10 的商品、组合规格库存和每日订单，确认后修改规格库存。',
    description_en: 'Use a seller certification key to read Qoo10 Japan products, combination-option stock and daily orders, and update option stock with confirmation.',
    description_es: "Usa una clave de certificación de vendedor para leer productos, existencias de combinaciones de opciones y pedidos diarios de Qoo10 Japan, y actualizar las existencias de opciones con confirmación.",
    description_fr: "Utilisez une clé de certification vendeur pour consulter les produits Qoo10 Japan, les stocks des combinaisons d’options et les commandes quotidiennes, et mettre à jour les stocks d’options avec confirmation.",
    description_ko: "판매자 인증 키로 Qoo10 Japan의 상품, 조합 옵션 재고, 일별 주문을 읽고 확인 후 옵션 재고를 업데이트합니다.",
    description_de: "Verwenden Sie einen Verkäufer-Zertifizierungsschlüssel, um Qoo10 Japan-Produkte, Bestände von Optionskombinationen und tägliche Bestellungen zu lesen und Optionsbestände mit Bestätigung zu aktualisieren.",
    description_ru: "Используйте ключ сертификации продавца для чтения товаров Qoo10 Japan, запасов комбинаций вариантов и ежедневных заказов, а также обновления запасов вариантов с подтверждением.",
    description_it: "Usa una chiave di certificazione del venditore per leggere prodotti, scorte delle combinazioni di opzioni e ordini giornalieri di Qoo10 Japan e aggiornare le scorte delle opzioni previa conferma.",
    description_ja: '販売者認証キーで Qoo10 の商品・組合せオプション在庫・日別注文を参照し、確認後にオプション在庫を更新します。',
    description_pt: 'Use a chave de certificação do vendedor para consultar produtos, estoque de opções combinadas e pedidos diários da Qoo10 Japan e alterar estoque mediante confirmação.',
    allowed_tools: tools, tool_policies: Object.fromEntries(tools.map(name => [name, toolPolicies[name]])), transport_template: transport,
    connection_setup: {
      requirement: 'provider_application',
      guide_url: 'https://api.qoo10.jp/GMKT.INC.Front.QAPIService/Document/QAPIGuideIndex.aspx',
      guide_label_zh: '打开 Qoo10 官方 API 指南', guide_label_en: 'Open the official Qoo10 API guide',
      guide_label_es: "Abrir la guía oficial de la API de Qoo10",
      guide_label_fr: "Ouvrir le guide officiel de l’API Qoo10",
      guide_label_ko: "Qoo10 공식 API 가이드 열기",
      guide_label_de: "Offiziellen Qoo10-API-Leitfaden öffnen",
      guide_label_ru: "Открыть официальное руководство Qoo10 API",
      guide_label_it: "Apri la guida ufficiale alle API Qoo10",
      guide_label_ja: 'Qoo10 公式 API ガイドを開く', guide_label_pt: 'Abrir o guia oficial da API Qoo10',
      instructions_zh: '需要已开通 API 的 Qoo10 日本商家账号，以及该店铺的 Seller Authorization Key（Certification Key）。请在官方平台完成密钥申请或生成，再填入下方；此处不需要店铺登录密码。密钥失效后重新连接。',
      instructions_en: 'Requires a Qoo10 Japan seller account with API access and its Seller Authorization Key (Certification Key). Obtain or generate the key on the official platform, then enter it below. Your shop login password is not needed here. Reconnect when the key expires.',
      instructions_es: "Requiere una cuenta de vendedor de Qoo10 Japan con acceso a la API y su Seller Authorization Key (Certification Key). Obtén o genera la clave en la plataforma oficial y después introdúcela a continuación. Aquí no se necesita la contraseña de inicio de sesión de tu tienda. Vuelve a conectar cuando la clave caduque.",
      instructions_fr: "Nécessite un compte vendeur Qoo10 Japan avec accès API et sa Seller Authorization Key (Certification Key). Obtenez ou générez la clé sur la plateforme officielle, puis saisissez-la ci-dessous. Le mot de passe de votre boutique n’est pas nécessaire ici. Reconnectez-vous lorsque la clé expire.",
      instructions_ko: "API 접근 권한이 있는 Qoo10 Japan 판매자 계정과 해당 Seller Authorization Key(Certification Key)가 필요합니다. 공식 플랫폼에서 키를 발급받거나 생성한 후 아래에 입력하세요. 상점 로그인 비밀번호는 필요하지 않습니다. 키가 만료되면 다시 연결하세요.",
      instructions_de: "Erfordert ein Qoo10 Japan-Verkäuferkonto mit API-Zugriff und dessen Seller Authorization Key (Certification Key). Fordern Sie den Schlüssel auf der offiziellen Plattform an oder erstellen Sie ihn dort und geben Sie ihn unten ein. Ihr Shop-Anmeldepasswort wird hier nicht benötigt. Stellen Sie die Verbindung erneut her, wenn der Schlüssel abläuft.",
      instructions_ru: "Нужны аккаунт продавца Qoo10 Japan с доступом к API и его Seller Authorization Key (Certification Key). Получите или создайте ключ на официальной платформе и введите ниже. Пароль магазина здесь не нужен. Подключитесь заново по истечении срока ключа.",
      instructions_it: "Richiede un account venditore Qoo10 Japan con accesso alle API e la relativa Seller Authorization Key (Certification Key). Ottieni o genera la chiave sulla piattaforma ufficiale, quindi inseriscila qui sotto. Qui non serve la password di accesso al negozio. Riconnettiti quando la chiave scade.",
      instructions_ja: 'API 利用可能な Qoo10 日本販売者アカウントと Seller Authorization Key（Certification Key）が必要です。公式プラットフォームでキーを申請・生成し、下記に入力します。店舗ログインのパスワードは不要です。キー失効時は再接続してください。',
      instructions_pt: 'Exige conta de vendedor Qoo10 Japan com acesso à API e Seller Authorization Key (Certification Key). Obtenha ou gere a chave na plataforma oficial e informe abaixo. A senha de login da loja não é necessária aqui. Reconecte quando a chave expirar.',
      fields: [{ key: 'certification_key', input: 'secret', storage: 'credential', format: 'secret', required: true,
        help_zh: '填写该店铺的 Seller Authorization Key（Certification Key），不是 API ID、密码或其他国家站点的密钥。',
        help_en: 'Use this Japan shop’s Seller Authorization Key (Certification Key), not an API ID, password or another country’s key.',
        help_es: "Usa la Seller Authorization Key (Certification Key) de esta tienda de Japón, no un ID de API, una contraseña ni una clave de otro país.",
        help_fr: "Utilisez la Seller Authorization Key (Certification Key) de cette boutique japonaise, et non un API ID, un mot de passe ou une clé d’un autre pays.",
        help_ko: "이 일본 상점의 Seller Authorization Key(Certification Key)를 사용하세요. API ID, 비밀번호, 다른 국가의 키는 사용하지 마세요.",
        help_de: "Verwenden Sie den Seller Authorization Key (Certification Key) dieses japanischen Shops, keine API ID, kein Passwort und keinen Schlüssel eines anderen Landes.",
        help_ru: "Используйте Seller Authorization Key (Certification Key) этого японского магазина, а не API ID, пароль или ключ другой страны.",
        help_it: "Usa la Seller Authorization Key (Certification Key) di questo negozio in Giappone, non un API ID, una password o la chiave di un altro paese.",
        help_ja: 'この日本ショップの Seller Authorization Key（Certification Key）を入力します。API ID、パスワード、他国サイトのキーではありません。',
        help_pt: 'Use a Seller Authorization Key (Certification Key) desta loja japonesa, não um API ID, senha ou chave de outro país.',
        label_zh: '商家认证密钥', label_en: 'Seller Certification Key',
        label_es: "Clave de certificación del vendedor",
        label_fr: "Clé de certification vendeur",
        label_ko: "Seller Certification Key",
        label_de: "Verkäufer-Zertifizierungsschlüssel",
        label_ru: "Seller Certification Key",
        label_it: "Seller Certification Key", label_ja: '販売者認証キー', label_pt: 'Chave de certificação do vendedor' }],
    },
  }, {
    id: 'futureshop', display_name: 'futureshop', category: 'commerce', auth_mode: 'local_api', local_api: { provider: 'futureshop' },
    setup_guide_id: 'futureshop',
    icon_svg: FUTURESHOP_ICON.svg, icon_source_url: FUTURESHOP_ICON.source_url, icon_source_sha256: FUTURESHOP_ICON.source_sha256,
    description_zh: '读取 futureshop 商品、订单和库存，确认后修改普通库存。需要获批的 API 接入信息，以及已登记的固定出口 IP。',
    description_en: 'Read futureshop products, orders and stock, and update regular stock with confirmation. Requires approved API access and a registered fixed outbound IP.',
    description_es: "Lee productos, pedidos y existencias de futureshop, y actualiza las existencias regulares con confirmación. Requiere acceso a la API aprobado y una IP de salida fija registrada.",
    description_fr: "Consultez les produits, les commandes et les stocks futureshop, et mettez à jour les stocks ordinaires avec confirmation. Nécessite un accès API approuvé et une adresse IP sortante fixe enregistrée.",
    description_ko: "futureshop의 상품, 주문, 재고를 읽고 확인 후 일반 재고를 업데이트합니다. 승인된 API 접근 권한과 등록된 고정 아웃바운드 IP가 필요합니다.",
    description_de: "Lesen Sie futureshop-Produkte, Bestellungen und Bestände und aktualisieren Sie reguläre Bestände mit Bestätigung. Erfordert genehmigten API-Zugriff und eine registrierte feste ausgehende IP-Adresse.",
    description_ru: "Читайте товары, заказы и запасы futureshop и обновляйте обычные запасы с подтверждением. Нужны одобренный доступ к API и зарегистрированный фиксированный исходящий IP.",
    description_it: "Leggi prodotti, ordini e scorte di futureshop e aggiorna le scorte ordinarie previa conferma. Richiede l'accesso alle API approvato e un IP fisso in uscita registrato.",
    description_ja: 'futureshop の商品・受注・在庫を参照し、確認後に通常在庫を更新します。承認済み API 接続情報と登録済み固定 IP が必要です。',
    description_pt: 'Consulte produtos, pedidos e estoque da futureshop e altere estoque regular mediante confirmação. Exige acesso aprovado à API e IP fixo de saída registrado.',
    allowed_tools: tools, tool_policies: Object.fromEntries(tools.map(name => [name, toolPolicies[name]])), transport_template: transport,
    connection_setup: {
      requirement: 'provider_application', guide_url: 'https://manual.future-shop.jp/api/',
      guide_label_zh: '打开 futureshop 官方接入指南', guide_label_en: 'Open the official futureshop API guide',
      guide_label_es: "Abrir la guía oficial de la API de futureshop",
      guide_label_fr: "Ouvrir le guide officiel de l’API futureshop",
      guide_label_ko: "futureshop 공식 API 가이드 열기",
      guide_label_de: "Offiziellen futureshop-API-Leitfaden öffnen",
      guide_label_ru: "Открыть официальное руководство futureshop API",
      guide_label_it: "Apri la guida ufficiale alle API futureshop",
      guide_label_ja: 'futureshop 公式 API ガイドを開く', guide_label_pt: 'Abrir o guia oficial da API futureshop',
      instructions_zh: '先完成 futureshop API 申请；服务商接入还需合作协议。填入官方下发的 API 域名、Client ID、Client Secret 和店铺 Key。运行 Orkas 的网络须使用已登记的固定出口 IP；配置本身不会提供固定 IP。每秒最多调用一次。',
      instructions_en: 'Complete futureshop API approval; service-provider integrations also require an alliance agreement. Enter the issued API domain, Client ID, Client Secret and shop key. Orkas must use your registered fixed outbound IP; configuring this connector does not supply one. Limited to one request per second.',
      instructions_es: "Completa la aprobación de acceso a la API de futureshop; las integraciones de proveedores de servicios también requieren un acuerdo de colaboración. Introduce el dominio de API, el Client ID, el Client Secret y la clave de tienda emitidos. Orkas debe usar tu IP de salida fija registrada; configurar este conector no proporciona una. Límite de una solicitud por segundo.",
      instructions_fr: "Obtenez l’approbation de l’API futureshop ; les intégrations de prestataires nécessitent aussi un accord de partenariat. Saisissez le domaine API, le Client ID, le Client Secret et la clé de boutique fournis. Orkas doit utiliser votre adresse IP sortante fixe enregistrée ; la configuration de ce connecteur n’en fournit pas. Limité à une requête par seconde.",
      instructions_ko: "futureshop API 승인을 완료하세요. 서비스 제공업체의 연동에는 제휴 계약도 필요합니다. 발급받은 API 도메인, Client ID, Client Secret, 상점 키를 입력하세요. Orkas는 등록한 고정 아웃바운드 IP를 사용해야 합니다. 이 커넥터를 설정해도 고정 IP가 제공되지는 않습니다. 요청은 초당 1회로 제한됩니다.",
      instructions_de: "Schließen Sie die futureshop-API-Genehmigung ab; Dienstleisterintegrationen erfordern zusätzlich eine Partnerschaftsvereinbarung. Geben Sie die ausgestellte API-Domain, Client ID, Client Secret und den Shopschlüssel ein. Orkas muss Ihre registrierte feste ausgehende IP-Adresse verwenden; die Konfiguration dieses Konnektors stellt keine bereit. Auf eine Anfrage pro Sekunde begrenzt.",
      instructions_ru: "Получите одобрение futureshop API; для интеграций поставщиков услуг также нужен партнёрский договор. Введите выданные домен API, Client ID, Client Secret и ключ магазина. Orkas должен использовать ваш зарегистрированный фиксированный исходящий IP; настройка коннектора не предоставляет такой IP. Ограничение — один запрос в секунду.",
      instructions_it: "Completa l'approvazione delle API futureshop; le integrazioni dei fornitori di servizi richiedono anche un accordo di alleanza. Inserisci il dominio API assegnato, Client ID, Client Secret e la chiave del negozio. Orkas deve usare il tuo IP fisso in uscita registrato; la configurazione di questo connettore non ne fornisce uno. Limite di una richiesta al secondo.",
      instructions_ja: 'futureshop API の利用申請を完了します。サービス提供者の連携にはアライアンス契約も必要です。発行された API ドメイン・Client ID・Client Secret・店舗キーを入力します。Orkas は登録済み固定 IP から接続する必要があり、この設定で固定 IP は提供されません。呼出は毎秒1回までです。',
      instructions_pt: 'Conclua a aprovação da API futureshop; integrações de prestadores também exigem acordo de parceria. Informe domínio da API, Client ID, Client Secret e chave da loja emitidos. Orkas deve usar seu IP fixo de saída registrado; esta configuração não fornece um IP. Limite de uma solicitação por segundo.',
      fields: [{ key: 'api_origin', input: 'text', storage: 'metadata', format: 'futureshop_api_origin', required: true,
        help_zh: '使用 API 申请获批后下发的 HTTPS 域名，不含路径；店铺前台网址不能代替 API 域名。',
        help_en: 'Use the HTTPS API domain issued on approval, without a path. The storefront URL is not the API domain.',
        help_es: "Usa el dominio HTTPS de la API emitido al aprobar el acceso, sin una ruta. La URL de la tienda no es el dominio de la API.",
        help_fr: "Utilisez le domaine API HTTPS fourni lors de l’approbation, sans chemin. L’URL de la vitrine n’est pas le domaine API.",
        help_ko: "승인 시 발급된 HTTPS API 도메인을 경로 없이 사용하세요. 상점 웹사이트 URL은 API 도메인이 아닙니다.",
        help_de: "Verwenden Sie die bei der Genehmigung ausgestellte HTTPS-API-Domain ohne Pfad. Die Shop-URL ist nicht die API-Domain.",
        help_ru: "Используйте выданный при одобрении HTTPS-домен API без пути. URL витрины не является доменом API.",
        help_it: "Usa il dominio API HTTPS assegnato al momento dell'approvazione, senza percorso. L'URL della vetrina non è il dominio API.",
        help_ja: '利用承認後に発行された HTTPS API ドメインをパスなしで入力します。ショップ公開 URL ではありません。',
        help_pt: 'Use o domínio HTTPS da API emitido após aprovação, sem caminho. A URL da vitrine não é o domínio da API.',
        label_zh: '官方下发的 API 域名', label_en: 'Issued API domain',
        label_es: "Dominio de API emitido",
        label_fr: "Domaine API fourni",
        label_ko: "발급된 API 도메인",
        label_de: "Ausgestellte API-Domain",
        label_ru: "Выданный домен API",
        label_it: "Dominio API assegnato", label_ja: '発行された API ドメイン', label_pt: 'Domínio da API emitido' },
      ...(['client_id', 'client_secret', 'shop_key'] as const).map(key => ({ key, input: 'secret' as const, storage: 'credential' as const,
        ...(key === 'shop_key' ? {
          help_zh: '复制此次 API 申请获批时下发的店铺 Key，需与上方域名及应用对应。',
          help_en: 'Copy the shop key issued with this approved API access; it must match the domain and application above.',
          help_es: "Copia la clave de tienda emitida con este acceso a la API aprobado; debe corresponder al dominio y a la aplicación anteriores.",
          help_fr: "Copiez la clé de boutique fournie avec cet accès API approuvé ; elle doit correspondre au domaine et à l’application ci-dessus.",
          help_ko: "이 승인된 API 접근 권한과 함께 발급된 상점 키를 복사하세요. 위 도메인 및 애플리케이션과 일치해야 합니다.",
          help_de: "Kopieren Sie den mit diesem genehmigten API-Zugriff ausgestellten Shopschlüssel; er muss zur obigen Domain und Anwendung passen.",
          help_ru: "Скопируйте ключ магазина, выданный вместе с этим одобренным доступом к API; он должен соответствовать домену и приложению выше.",
          help_it: "Copia la chiave del negozio rilasciata con questo accesso alle API approvato; deve corrispondere al dominio e all'applicazione indicati sopra.",
          help_ja: '今回の API 利用承認で発行された店舗キーをコピーします。上記のドメイン・アプリと対応する必要があります。',
          help_pt: 'Copie a chave da loja emitida com este acesso aprovado; ela deve corresponder ao domínio e app acima.',
        } : applicationCredentialHelp('futureshop', key)),
        format: key === 'client_id' ? 'client_id' as const : 'secret' as const, required: true,
        label_zh: key === 'shop_key' ? '店铺 Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
        label_en: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_es: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_fr: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ko: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_de: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ru: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_it: key === 'shop_key' ? 'Shop Key' : key === 'client_id' ? 'Client ID' : 'Client Secret',
        label_ja: key === 'shop_key' ? '店舗キー' : key === 'client_id' ? 'Client ID' : 'Client Secret',
        label_pt: key === 'shop_key' ? 'Chave da loja' : key === 'client_id' ? 'Client ID' : 'Client Secret',
      }))],
    },
  }, {
    id: 'yahoo-shopping', display_name: 'Yahoo! Shopping', category: 'commerce', auth_mode: 'local_api', local_api: { provider: 'yahoo_shopping' },
    setup_guide_id: 'yahoo-shopping',
    icon_svg: YAHOO_SHOPPING_ICON.svg, icon_source_url: YAHOO_SHOPPING_ICON.source_url, icon_source_sha256: YAHOO_SHOPPING_ICON.source_sha256,
    description_zh: '连接日本 Yahoo! Shopping，查询商品、库存和订单，确认后修改库存。生产环境的订单 API 需要单独申请并登记出口 IP。',
    description_en: 'Connect Yahoo! Shopping Japan to read products, stock and orders, and update stock with confirmation. Production order APIs require separate approval and outbound IP registration.',
    description_es: "Conecta Yahoo! Shopping Japan para leer productos, existencias y pedidos, y actualizar existencias con confirmación. Las API de pedidos en producción requieren una aprobación independiente y el registro de la IP de salida.",
    description_fr: "Connectez Yahoo! Shopping Japan pour consulter les produits, les stocks et les commandes, et mettre à jour les stocks avec confirmation. Les API de commandes en production nécessitent une approbation distincte et l’enregistrement d’une adresse IP sortante.",
    description_ko: "Yahoo! Shopping Japan을 연결해 상품, 재고, 주문을 읽고 확인 후 재고를 업데이트합니다. 프로덕션 주문 API에는 별도 승인과 아웃바운드 IP 등록이 필요합니다.",
    description_de: "Verbinden Sie Yahoo! Shopping Japan, um Produkte, Bestände und Bestellungen zu lesen und Bestände mit Bestätigung zu aktualisieren. Produktions-Bestell-APIs erfordern eine separate Genehmigung und die Registrierung einer ausgehenden IP-Adresse.",
    description_ru: "Подключите Yahoo! Shopping Japan для чтения товаров, запасов и заказов, а также обновления запасов с подтверждением. Производственные API заказов требуют отдельного одобрения и регистрации исходящего IP.",
    description_it: "Collega Yahoo! Shopping Japan per leggere prodotti, scorte e ordini e aggiornare le scorte previa conferma. Le API degli ordini in produzione richiedono un'approvazione separata e la registrazione dell'IP in uscita.",
    description_ja: 'Yahoo!ショッピングの商品・在庫・注文を参照し、確認後に在庫を更新します。本番の注文 API には別途利用申請と接続元 IP 登録が必要です。',
    description_pt: 'Conecte Yahoo! Shopping Japan para consultar produtos, estoque e pedidos e alterar estoque mediante confirmação. APIs de pedidos em produção exigem aprovação e registro do IP de saída.',
    allowed_tools: tools, tool_policies: Object.fromEntries(tools.map(name => [name, toolPolicies[name]])), transport_template: transport,
    connection_setup: {
      requirement: 'provider_application', callback_url: LOCAL_API_REDIRECT_URI,
      ...CALLBACK_HELP,
      guide_url: 'https://developer.yahoo.co.jp/webapi/shopping/introduction.html',
      guide_label_zh: '打开 Yahoo! Shopping 官方接入指南', guide_label_en: 'Open the official Yahoo! Shopping setup guide',
      guide_label_es: "Abrir la guía oficial de configuración de Yahoo! Shopping",
      guide_label_fr: "Ouvrir le guide officiel de configuration de Yahoo! Shopping",
      guide_label_ko: "Yahoo! Shopping 공식 설정 가이드 열기",
      guide_label_de: "Offiziellen Einrichtungsleitfaden für Yahoo! Shopping öffnen",
      guide_label_ru: "Открыть официальное руководство по настройке Yahoo! Shopping",
      guide_label_it: "Apri la guida ufficiale alla configurazione di Yahoo! Shopping",
      guide_label_ja: 'Yahoo!ショッピング公式導入ガイドを開く', guide_label_pt: 'Abrir o guia oficial Yahoo! Shopping',
      instructions_zh: '使用具有「ストア向け操作関連の機能」权限的 Yahoo! Shopping 应用，配置下方回调地址。生产环境登录账号须关联店铺员工的 Business ID。生产订单功能另需申请和登记出口 IP；可选填官方公开密钥及版本，将相关接口的重新授权周期从 12 小时延长至最多 4 周。',
      instructions_en: 'Use a Yahoo! Shopping app with store-operation scope and register the callback below. In production, the login must link to a Business ID registered as shop staff. Production order access needs separate approval and a registered outbound IP. An optional provider-issued public key and version extend reauthorization for those APIs from 12 hours to up to four weeks.',
      instructions_es: "Usa una aplicación de Yahoo! Shopping con el ámbito de permisos de operaciones de tienda y registra la URL de retorno que aparece a continuación. En producción, la cuenta de inicio de sesión debe estar vinculada a un Business ID registrado como personal de la tienda. El acceso a pedidos en producción requiere una aprobación independiente y una IP de salida registrada. Una clave pública opcional emitida por el proveedor y su versión amplían el intervalo de reautorización de esas API de 12 horas a un máximo de cuatro semanas.",
      instructions_fr: "Utilisez une application Yahoo! Shopping avec la portée de gestion de boutique et enregistrez l’URL de rappel ci-dessous. En production, le compte de connexion doit être lié à un Business ID enregistré comme membre du personnel de la boutique. L’accès aux commandes en production nécessite une approbation distincte et une adresse IP sortante enregistrée. Une clé publique facultative émise par le fournisseur et sa version permettent d’étendre l’intervalle de réautorisation de ces API de 12 heures à quatre semaines au maximum.",
      instructions_ko: "상점 운영 권한 범위가 있는 Yahoo! Shopping 앱을 사용하고 아래 콜백을 등록하세요. 프로덕션에서는 로그인 계정이 상점 직원으로 등록된 Business ID와 연결되어 있어야 합니다. 프로덕션 주문 접근에는 별도 승인과 아웃바운드 IP 등록이 필요합니다. 선택 사항인 제공업체 발급 공개 키와 버전을 사용하면 해당 API의 재승인 주기가 12시간에서 최대 4주로 늘어납니다.",
      instructions_de: "Verwenden Sie eine Yahoo! Shopping-App mit dem Berechtigungsbereich für den Shopbetrieb und registrieren Sie den unten angegebenen Callback. In der Produktionsumgebung muss die Anmeldung mit einer Business ID verknüpft sein, die als Shopmitarbeiter registriert ist. Produktions-Bestellzugriff erfordert eine separate Genehmigung und eine registrierte ausgehende IP-Adresse. Ein optionaler öffentlicher Schlüssel des Anbieters samt Version verlängert das Intervall zur erneuten Autorisierung dieser APIs von 12 Stunden auf bis zu vier Wochen.",
      instructions_ru: "Используйте приложение Yahoo! Shopping с областью доступа для операций магазина и зарегистрируйте обратный вызов ниже. В производственной среде аккаунт входа должен быть связан с Business ID, зарегистрированным как сотрудник магазина. Производственный доступ к заказам требует отдельного одобрения и регистрации исходящего IP. Необязательные открытый ключ поставщика и его версия увеличивают срок до повторной авторизации этих API с 12 часов до четырёх недель максимум.",
      instructions_it: "Usa un'app Yahoo! Shopping con ambito di autorizzazione store-operation e registra il callback qui sotto. In produzione, l'account di accesso deve essere collegato a un Business ID registrato come personale del negozio. L'accesso agli ordini in produzione richiede un'approvazione separata e un IP in uscita registrato. Una chiave pubblica facoltativa rilasciata dal fornitore, insieme alla sua versione, estende l'intervallo di riautorizzazione per queste API da 12 ore fino a quattro settimane.",
      instructions_ja: '「ストア向け操作関連の機能」権限を持つアプリに下記コールバックを登録します。本番ではログイン ID と店舗従業員のビジネス ID の紐付けが必要です。本番の注文 API は別途申請と接続元 IP 登録が必要です。任意の公式公開鍵とバージョンを設定すると、対象 API の再認可間隔が12時間から最大4週間になります。',
      instructions_pt: 'Use app Yahoo! Shopping com permissão de operações da loja e registre o callback abaixo. Em produção, o login deve vincular um Business ID de funcionário da loja. Pedidos em produção exigem aprovação separada e IP de saída registrado. Chave pública e versão opcionais estendem a reautorização dessas APIs de 12 horas para até quatro semanas.',
      fields: [{ key: 'seller_id', input: 'text', storage: 'metadata', format: 'yahoo_seller_id', required: true,
        help_zh: '填写目标店铺的ストアアカウント，不是登录用的 Yahoo! JAPAN ID 或 Business ID。',
        help_en: 'Enter the intended shop’s store account, not the login Yahoo! JAPAN ID or Business ID.',
        help_es: "Introduce la cuenta de tienda de la tienda que quieras conectar, no el Yahoo! JAPAN ID de inicio de sesión ni el Business ID.",
        help_fr: "Saisissez le compte de boutique voulu, et non le Yahoo! JAPAN ID ou le Business ID de connexion.",
        help_ko: "연결할 상점의 상점 계정을 입력하세요. 로그인용 Yahoo! JAPAN ID나 Business ID는 사용하지 마세요.",
        help_de: "Geben Sie das Store-Konto des gewünschten Shops ein, nicht die Yahoo! JAPAN ID oder Business ID zur Anmeldung.",
        help_ru: "Введите аккаунт нужного магазина, а не Yahoo! JAPAN ID для входа или Business ID.",
        help_it: "Inserisci l'account del negozio desiderato, non lo Yahoo! JAPAN ID di accesso o il Business ID.",
        help_ja: '対象店舗のストアアカウントを入力します。ログイン用 Yahoo! JAPAN ID やビジネス ID ではありません。',
        help_pt: 'Informe a conta da loja desejada, não o Yahoo! JAPAN ID de login nem o Business ID.',
        label_zh: '店铺账号（Seller ID）', label_en: 'Seller ID',
        label_es: "ID del vendedor",
        label_fr: "ID du vendeur",
        label_ko: "Seller ID",
        label_de: "Verkäufer-ID",
        label_ru: "Seller ID",
        label_it: "Seller ID", label_ja: 'ストアアカウント', label_pt: 'Seller ID' },
      ...(['client_id', 'client_secret'] as const).map(key => ({ key, input: 'secret' as const, storage: 'credential' as const,
        ...applicationCredentialHelp('Yahoo! Shopping', key),
        format: key === 'client_id' ? 'client_id' as const : 'secret' as const, required: true,
        label_zh: key === 'client_id' ? 'Client ID' : 'Client Secret', label_en: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_es: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_fr: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ko: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_de: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_ru: key === 'client_id' ? 'Client ID' : 'Client Secret',
    label_it: key === 'client_id' ? 'Client ID' : 'Client Secret',
        label_ja: key === 'client_id' ? 'Client ID' : 'Client Secret', label_pt: key === 'client_id' ? 'Client ID' : 'Client Secret' })),
      { key: 'public_key', input: 'secret', storage: 'credential', format: 'yahoo_public_key', required: false,
        help_zh: '可复制官方发放的 PEM 或 Base64 公钥，并同时填写版本号；不需要私钥。留空仍可授权，但订单接口可能更频繁要求重新授权。',
        help_en: 'Optional provider-issued PEM or Base64 public key, together with its version. No private key is needed. Leaving both blank may require more frequent order API reauthorization.',
        help_es: "Clave pública opcional en formato PEM o Base64 emitida por el proveedor, junto con su versión. No se necesita una clave privada. Dejar ambos campos en blanco puede requerir una reautorización más frecuente de la API de pedidos.",
        help_fr: "Clé publique facultative au format PEM ou Base64, émise par le fournisseur, avec sa version. Aucune clé privée n’est nécessaire. Si vous laissez les deux champs vides, une réautorisation plus fréquente de l’API de commandes peut être nécessaire.",
        help_ko: "선택 사항인 제공업체 발급 PEM 또는 Base64 공개 키와 해당 버전입니다. 개인 키는 필요하지 않습니다. 두 항목을 모두 비워 두면 주문 API를 더 자주 재승인해야 할 수 있습니다.",
        help_de: "Optionaler öffentlicher Schlüssel des Anbieters im PEM- oder Base64-Format zusammen mit seiner Version. Ein privater Schlüssel ist nicht erforderlich. Wenn beide Felder leer bleiben, muss die Bestell-API möglicherweise häufiger erneut autorisiert werden.",
        help_ru: "Необязательный открытый ключ, выданный поставщиком, в формате PEM или Base64, вместе с его версией. Закрытый ключ не нужен. Если оставить оба поля пустыми, повторная авторизация API заказов может требоваться чаще.",
        help_it: "Chiave pubblica PEM o Base64 facoltativa rilasciata dal fornitore, insieme alla sua versione. Non serve alcuna chiave privata. Lasciare entrambi i campi vuoti può richiedere una riautorizzazione più frequente delle API degli ordini.",
        help_ja: '任意で公式発行の PEM または Base64 公開鍵とバージョンを入力します。秘密鍵は不要です。両方を空欄にすると注文 API の再認可頻度が高くなる場合があります。',
        help_pt: 'Chave pública oficial opcional em PEM ou Base64, junto com sua versão. Não é necessária chave privada. Deixar ambos vazios pode exigir reautorização mais frequente da API de pedidos.',
        label_zh: '官方公开密钥（可选）', label_en: 'Provider public key (optional)',
        label_es: "Clave pública del proveedor (opcional)",
        label_fr: "Clé publique du fournisseur (facultatif)",
        label_ko: "제공업체 공개 키(선택 사항)",
        label_de: "Öffentlicher Schlüssel des Anbieters (optional)",
        label_ru: "Открытый ключ поставщика (необязательно)",
        label_it: "Chiave pubblica del fornitore (facoltativa)", label_ja: '公式公開鍵（任意）', label_pt: 'Chave pública do provedor (opcional)' },
      { key: 'key_version', input: 'text', storage: 'metadata', format: 'yahoo_key_version', required: false,
        help_zh: '填写与上方公钥一同发放的数字版本；未设置公钥时留空。',
        help_en: 'Enter the numeric version issued with the public key above; leave blank when no key is supplied.',
        help_es: "Introduce la versión numérica emitida con la clave pública anterior; deja el campo en blanco si no se proporciona una clave.",
        help_fr: "Saisissez la version numérique fournie avec la clé publique ci-dessus ; laissez ce champ vide si aucune clé n’est fournie.",
        help_ko: "위 공개 키와 함께 발급된 숫자 버전을 입력하세요. 키를 입력하지 않았다면 비워 두세요.",
        help_de: "Geben Sie die mit dem obigen öffentlichen Schlüssel ausgestellte numerische Version ein; lassen Sie das Feld leer, wenn kein Schlüssel angegeben wird.",
        help_ru: "Введите числовую версию, выданную вместе с открытым ключом выше; оставьте поле пустым, если ключ не указан.",
        help_it: "Inserisci la versione numerica rilasciata insieme alla chiave pubblica indicata sopra; lascia vuoto se non viene fornita alcuna chiave.",
        help_ja: '上記公開鍵と共に発行された数字のバージョンを入力します。公開鍵なしの場合は空欄にします。',
        help_pt: 'Informe a versão numérica emitida com a chave acima; deixe vazia se não informar a chave.',
        label_zh: '公开密钥版本（与密钥同时填写）', label_en: 'Public key version (required with key)',
        label_es: "Versión de la clave pública (obligatoria con clave)",
        label_fr: "Version de la clé publique (requise avec la clé)",
        label_ko: "공개 키 버전(키 입력 시 필수)",
        label_de: "Version des öffentlichen Schlüssels (bei Schlüsselangabe erforderlich)",
        label_ru: "Версия открытого ключа (обязательна с ключом)",
        label_it: "Versione della chiave pubblica (obbligatoria con la chiave)", label_ja: '公開鍵バージョン（鍵設定時は必須）', label_pt: 'Versão da chave pública (exigida com a chave)' }],
    },
  }];
}
