/** Seller-owned applications; platform eligibility is not bypassed by desktop authorization. */
import type { CatalogEntry, ConnectorActionPolicy, Transport } from './types';
import { SHOPEE_ICON, TIKTOK_SHOP_ICON } from './catalog-seller-brand-icons';
import { LOCAL_API_REDIRECT_URI } from './oauth-redirect';

export function sellerMarketplaceEntries(
  policies: Record<string, ConnectorActionPolicy>, transport: Transport,
): CatalogEntry[] {
  const tools = ['list_capabilities', 'describe_action', 'execute_read', 'execute_high_impact'];
  const toolPolicies = Object.fromEntries(tools.map((name) => [name, policies[name]]));
  return [
    {
      id: 'shopee', setup_guide_id: 'shopee', display_name: 'Shopee', category: 'commerce',
      icon_svg: SHOPEE_ICON.svg, icon_source_url: SHOPEE_ICON.source_url, icon_source_sha256: SHOPEE_ICON.source_sha256,
      description_zh: '使用卖家自有 Open Platform 应用授权店铺，读取商品、订单和仓库，并确认后修改价格与库存。需要平台批准的应用和 API 权限。',
      description_en: 'Authorize a shop with your own Open Platform app to read products, orders and warehouses, and update prices and stock with confirmation. An approved app and API permissions are required.',
      description_es: "Autoriza una tienda con tu propia aplicación de Open Platform para leer productos, pedidos y almacenes, y actualizar precios y existencias con confirmación. Se requieren una aplicación aprobada y permisos de API.",
      description_fr: "Autorisez une boutique avec votre propre application Open Platform pour consulter les produits, les commandes et les entrepôts, et mettre à jour les prix et les stocks avec confirmation. Une application approuvée et des autorisations API sont requises.",
      description_ko: "본인의 Open Platform 앱으로 상점을 승인해 상품, 주문, 창고를 읽고 확인 후 가격과 재고를 업데이트합니다. 승인된 앱과 API 권한이 필요합니다.",
      description_de: "Autorisieren Sie einen Shop mit Ihrer eigenen Open Platform-App, um Produkte, Bestellungen und Lager zu lesen und Preise und Bestände mit Bestätigung zu aktualisieren. Eine genehmigte App und API-Berechtigungen sind erforderlich.",
      description_ru: "Авторизуйте магазин через собственное приложение Open Platform для чтения товаров, заказов и складов, а также обновления цен и запасов с подтверждением. Нужны одобренное приложение и разрешения API.",
      description_it: "Autorizza un negozio con la tua app Open Platform per leggere prodotti, ordini e magazzini e aggiornare prezzi e scorte previa conferma. Sono necessarie un'app approvata e le autorizzazioni API.",
      description_ja: "自身の Open Platform アプリで店舗を認証し、商品、注文、倉庫を参照して、確認後に価格と在庫を更新します。アプリと API 権限の承認が必要です。",
      description_pt: "Autorize uma loja com seu próprio app Open Platform para consultar produtos, pedidos e depósitos e atualizar preços e estoque mediante confirmação. Exige app e permissões API aprovados.",
      auth_mode: 'local_api', local_api: { provider: 'shopee' },
      connection_setup: {
        callback_url: LOCAL_API_REDIRECT_URI,
        callback_help_zh: '在应用正式环境的 Redirect URL Domain 填 orkas.ai（只填域名，无需自建回调服务）。',
        callback_help_en: 'Set the production Redirect URL Domain to orkas.ai (domain only; no callback server needed).',
        callback_help_es: "Establece Redirect URL Domain de producción en orkas.ai (solo el dominio; no se necesita un servidor para la URL de retorno).",
        callback_help_fr: "Définissez le Redirect URL Domain de production sur orkas.ai (domaine uniquement ; aucun serveur de rappel nécessaire).",
        callback_help_ko: "프로덕션 Redirect URL Domain을 orkas.ai로 설정하세요(도메인만 입력하며 콜백 서버는 필요하지 않습니다).",
        callback_help_de: "Setzen Sie die Redirect URL Domain der Produktionsumgebung auf orkas.ai (nur die Domain; kein Callback-Server erforderlich).",
        callback_help_ru: "Установите производственный Redirect URL Domain в orkas.ai (только домен; сервер обратного вызова не нужен).",
        callback_help_it: "Imposta Redirect URL Domain per l'ambiente di produzione su orkas.ai (solo il dominio; non serve un server di callback).",
        callback_help_ja: "本番の Redirect URL Domain に orkas.ai を設定してください（ドメインのみ。コールバックサーバーの用意は不要です）。",
        callback_help_pt: "Defina o Redirect URL Domain de produção como orkas.ai (apenas o domínio; não é necessário servidor de callback).",
        requirement: 'provider_application',
        instructions_zh: '需要已获批的 Seller in House System 应用，以及店铺、商品、订单和价格/库存修改权限。仅连接真实店铺，请用店铺账号授权（非主账号或子账号）；个人卖家资格以所在市场为准。',
        instructions_en: 'Requires an approved Seller in House System app with Shop, Product and Order permissions, including price/stock updates. Connect a production shop using its shop account, not a main or sub-account. Individual-seller eligibility varies by market.',
        instructions_es: "Requiere una aplicación Seller in House System aprobada con permisos Shop, Product y Order, incluidas las actualizaciones de precios y existencias. Conecta una tienda de producción con su cuenta de tienda, no con una cuenta principal ni una subcuenta. Los requisitos de elegibilidad para vendedores individuales varían según el mercado.",
        instructions_fr: "Nécessite une application Seller in House System approuvée avec les autorisations Shop, Product et Order, y compris les mises à jour de prix et de stocks. Connectez une boutique de production avec son compte de boutique, et non un compte principal ou secondaire. L’éligibilité des vendeurs individuels varie selon le marché.",
        instructions_ko: "가격 및 재고 업데이트를 포함한 Shop, Product, Order 권한이 있는 승인된 Seller in House System 앱이 필요합니다. 주 계정이나 하위 계정이 아닌 상점 계정으로 프로덕션 상점을 연결하세요. 개인 판매자 자격 요건은 시장마다 다릅니다.",
        instructions_de: "Erfordert eine genehmigte Seller in House System-App mit Shop-, Product- und Order-Berechtigungen einschließlich Preis-/Bestandsaktualisierungen. Verbinden Sie einen Produktionsshop mit seinem Shopkonto, nicht mit einem Haupt- oder Unterkonto. Die Zulassung einzelner Verkäufer variiert je nach Markt.",
        instructions_ru: "Нужно одобренное приложение Seller in House System с разрешениями Shop, Product и Order, включая обновление цен и запасов. Подключайте производственный магазин через его аккаунт магазина, а не основной или подчинённый аккаунт. Доступность для индивидуальных продавцов зависит от рынка.",
        instructions_it: "Richiede un'app Seller in House System approvata con le autorizzazioni Shop, Product e Order, inclusi gli aggiornamenti di prezzi e scorte. Collega un negozio in produzione usando il relativo account del negozio, non un account principale o secondario. L'idoneità dei venditori individuali varia in base al mercato.",
        instructions_ja: "Shop、Product、Order 権限（価格・在庫更新を含む）が承認された Seller in House System アプリが必要です。本番店舗のショップアカウントで接続してください。メイン・サブアカウントは使用できません。個人販売者の申請資格は市場により異なります。",
        instructions_pt: "Exige app Seller in House System aprovado com permissões Shop, Product e Order, incluindo atualizações de preço/estoque. Conecte uma loja de produção com a conta da própria loja, não uma conta principal ou subconta. A elegibilidade de vendedores individuais varia por mercado.",
        guide_url: 'https://open.shopee.com/developer-guide/20',
        guide_label_zh: '查看 Shopee 官方应用与授权指南', guide_label_en: 'Open the official Shopee authorization guide',
        guide_label_es: "Abrir la guía oficial de autorización de Shopee",
        guide_label_fr: "Ouvrir le guide officiel d’autorisation Shopee",
        guide_label_ko: "Shopee 공식 승인 가이드 열기",
        guide_label_de: "Offiziellen Leitfaden zur Shopee-Autorisierung öffnen",
        guide_label_ru: "Открыть официальное руководство по авторизации Shopee",
        guide_label_it: "Apri la guida ufficiale all'autorizzazione di Shopee", guide_label_ja: "Shopee 公式認証ガイドを開く", guide_label_pt: "Abrir guia oficial de autorização Shopee",
        fields: [
          { key: 'region', input: 'choice', storage: 'metadata', required: true, format: 'shopee_region', label_zh: '开放平台区域', label_en: 'Open Platform region',
          label_es: "Región de Open Platform",
          label_fr: "Région Open Platform",
          label_ko: "Open Platform 지역",
          label_de: "Open Platform-Region",
          label_ru: "Регион Open Platform",
          label_it: "Regione di Open Platform", label_ja: "Open Platform の地域", label_pt: "Região da Open Platform",
            help_zh: '选择管理该应用的开放平台站点，不是店铺销售市场。', help_en: 'Select the Open Platform site where you manage the app, not the shop’s sales market.',
            help_es: "Selecciona el sitio de Open Platform donde administras la aplicación, no el mercado de ventas de la tienda.",
            help_fr: "Sélectionnez le site Open Platform où vous gérez l’application, et non le marché de vente de la boutique.",
            help_ko: "상점의 판매 시장이 아닌 앱을 관리하는 Open Platform 사이트를 선택하세요.",
            help_de: "Wählen Sie die Open Platform-Website, auf der Sie die App verwalten, nicht den Absatzmarkt des Shops.",
            help_ru: "Выберите сайт Open Platform, на котором вы управляете приложением, а не рынок продаж магазина.",
            help_it: "Seleziona il sito Open Platform in cui gestisci l'app, non il mercato di vendita del negozio.", help_ja: "店舗の販売市場ではなく、アプリを管理している Open Platform のサイトを選択してください。", help_pt: "Selecione o site Open Platform onde gerencia o app, não o mercado de vendas da loja.",
            options: [{ value: 'global', label_zh: '全球（open.shopee.com）', label_en: 'Global (open.shopee.com)',
            label_es: "Global (open.shopee.com)",
            label_fr: "Monde (open.shopee.com)",
            label_ko: "글로벌(open.shopee.com)",
            label_de: "Global (open.shopee.com)",
            label_ru: "Глобальный (open.shopee.com)",
            label_it: "Globale (open.shopee.com)", label_ja: "グローバル（open.shopee.com）", label_pt: "Global (open.shopee.com)" }, { value: 'cn', label_zh: '中国大陆（open.shopee.cn）', label_en: 'Mainland China (open.shopee.cn)',
label_es: "China continental (open.shopee.cn)",
label_fr: "Chine continentale (open.shopee.cn)",
label_ko: "중국 본토(open.shopee.cn)",
label_de: "Festlandchina (open.shopee.cn)",
label_ru: "Материковый Китай (open.shopee.cn)",
label_it: "Cina continentale (open.shopee.cn)", label_ja: "中国本土（open.shopee.cn）", label_pt: "China continental (open.shopee.cn)" }, { value: 'br', label_zh: '巴西（open.shopee.com.br）', label_en: 'Brazil (open.shopee.com.br)',
label_es: "Brasil (open.shopee.com.br)",
label_fr: "Brésil (open.shopee.com.br)",
label_ko: "브라질(open.shopee.com.br)",
label_de: "Brasilien (open.shopee.com.br)",
label_ru: "Бразилия (open.shopee.com.br)",
label_it: "Brasile (open.shopee.com.br)", label_ja: "ブラジル（open.shopee.com.br）", label_pt: "Brasil (open.shopee.com.br)" }] },
          { key: 'shop_id', input: 'text', storage: 'metadata', required: true, format: 'shopee_id', label_zh: '店铺 ID', label_en: 'Shop ID',
          label_es: "ID de la tienda",
          label_fr: "ID de la boutique",
          label_ko: "Shop ID",
          label_de: "Shop-ID",
          label_ru: "Shop ID",
          label_it: "Shop ID", label_ja: "ショップ ID", label_pt: "ID da loja",
            help_zh: '从店铺链接 shop/ 后或 Open Platform 店铺资料中复制数字 ID，不是用户名或 Merchant ID。', help_en: 'Copy the numeric ID after shop/ in the shop URL or from Open Platform shop details, not a username or Merchant ID.',
            help_es: "Copia el ID numérico que aparece después de shop/ en la URL de la tienda o en los detalles de la tienda en Open Platform, no un nombre de usuario ni un Merchant ID.",
            help_fr: "Copiez l’ID numérique après shop/ dans l’URL de la boutique ou depuis les détails de la boutique dans Open Platform, et non un nom d’utilisateur ou un Merchant ID.",
            help_ko: "상점 URL에서 shop/ 뒤의 숫자 ID 또는 Open Platform 상점 상세 정보의 ID를 복사하세요. 사용자 이름이나 Merchant ID가 아닙니다.",
            help_de: "Kopieren Sie die numerische ID nach shop/ in der Shop-URL oder aus den Shopdetails in Open Platform, keinen Benutzernamen und keine Merchant ID.",
            help_ru: "Скопируйте числовой ID после shop/ в URL магазина или из сведений о магазине в Open Platform, а не имя пользователя или Merchant ID.",
            help_it: "Copia l'ID numerico dopo shop/ nell'URL del negozio oppure dai dettagli del negozio in Open Platform, non un nome utente o un Merchant ID.", help_ja: "ショップ URL の shop/ の後、または Open Platform の店舗詳細にある数値 ID をコピーしてください。ユーザー名や Merchant ID ではありません。", help_pt: "Copie o ID numérico após shop/ na URL da loja ou nos detalhes da loja na Open Platform; não use nome de usuário nem Merchant ID." },
          { key: 'partner_id', input: 'text', storage: 'credential', required: true, format: 'shopee_id', label_zh: 'Partner ID', label_en: 'Partner ID',
          label_es: "Partner ID",
          label_fr: "Partner ID",
          label_ko: "Partner ID",
          label_de: "Partner ID",
          label_ru: "Partner ID",
          label_it: "Partner ID", label_ja: "Partner ID", label_pt: "Partner ID",
            help_zh: 'Open Platform > App List > 应用详情，复制正式环境的 Partner ID（非 Test Partner ID）。', help_en: 'Open Platform > App List > app details: copy the production Partner ID, not the Test Partner ID.',
            help_es: "Open Platform > Lista de aplicaciones > Detalles de la aplicación: copia el Partner ID de producción, no el Test Partner ID.",
            help_fr: "Open Platform > App List > détails de l’application : copiez le Partner ID de production, et non le Test Partner ID.",
            help_ko: "Open Platform > App List > 앱 상세 정보에서 Test Partner ID가 아닌 프로덕션 Partner ID를 복사하세요.",
            help_de: "Open Platform > App List > App-Details: Kopieren Sie die Produktions-Partner ID, nicht die Test Partner ID.",
            help_ru: "Open Platform > App List > сведения о приложении: скопируйте производственный Partner ID, а не Test Partner ID.",
            help_it: "Open Platform > App List > app details: copia il Partner ID di produzione, non il Test Partner ID.", help_ja: "Open Platform > App List > アプリの詳細から本番の Partner ID をコピーしてください。Test Partner ID ではありません。", help_pt: "Em Open Platform > App List > detalhes do app, copie o Partner ID de produção, não o Test Partner ID." },
          { key: 'partner_key', input: 'secret', storage: 'credential', required: true, format: 'secret', label_zh: 'Partner Key', label_en: 'Partner Key',
          label_es: "Partner Key",
          label_fr: "Partner Key",
          label_ko: "Partner Key",
          label_de: "Partner Key",
          label_ru: "Partner Key",
          label_it: "Partner Key", label_ja: "Partner Key", label_pt: "Partner Key",
            help_zh: '在同一应用详情页复制正式环境的 Partner Key（非 Test Key）。', help_en: 'Copy the production Partner Key from the same app details page, not the Test Key.',
            help_es: "Copia la Partner Key de producción de la misma página de detalles de la aplicación, no la Test Key.",
            help_fr: "Copiez la Partner Key de production depuis la même page de détails de l’application, et non la Test Key.",
            help_ko: "같은 앱 상세 정보 페이지에서 Test Key가 아닌 프로덕션 Partner Key를 복사하세요.",
            help_de: "Kopieren Sie den Produktions-Partner Key von derselben App-Detailseite, nicht den Test Key.",
            help_ru: "Скопируйте производственный Partner Key с той же страницы сведений о приложении, а не Test Key.",
            help_it: "Copia il Partner Key di produzione dalla stessa pagina dei dettagli dell'app, non il Test Key.", help_ja: "同じアプリの詳細画面から本番の Partner Key をコピーしてください。Test Key ではありません。", help_pt: "Copie a Partner Key de produção da mesma página de detalhes do app, não a Test Key." },
        ],
      },
      allowed_tools: tools, tool_policies: toolPolicies, transport_template: transport,
    },
    {
      id: 'tiktok-shop', setup_guide_id: 'tiktok-shop', display_name: 'TikTok Shop', category: 'commerce',
      icon_svg: TIKTOK_SHOP_ICON.svg, icon_source_url: TIKTOK_SHOP_ICON.source_url, icon_source_sha256: TIKTOK_SHOP_ICON.source_sha256,
      description_zh: '使用卖家自有 TikTok Shop 应用授权店铺，读取商品、订单和仓库，并确认后修改价格与库存；不接入 TikTok 内容账号。',
      description_en: 'Authorize your shop using a seller-owned TikTok Shop app, read products, orders and warehouses, and update prices and stock with confirmation. This is not a TikTok content-account connector.',
      description_es: "Autoriza tu tienda con una aplicación de TikTok Shop propiedad del vendedor, consulta productos, pedidos y almacenes, y actualiza precios y existencias con confirmación. Este no es un conector para cuentas de contenido de TikTok.",
      description_fr: "Autorisez votre boutique avec une application TikTok Shop appartenant au vendeur, consultez les produits, les commandes et les entrepôts, et mettez à jour les prix et les stocks avec confirmation. Il ne s’agit pas d’un connecteur de compte de contenu TikTok.",
      description_ko: "판매자 소유의 TikTok Shop 앱으로 상점을 승인해 상품, 주문, 창고를 읽고 확인 후 가격과 재고를 업데이트합니다. TikTok 콘텐츠 계정 커넥터가 아닙니다.",
      description_de: "Autorisieren Sie Ihren Shop mit einer eigenen TikTok Shop-App des Verkäufers, lesen Sie Produkte, Bestellungen und Lager und aktualisieren Sie Preise und Bestände mit Bestätigung. Dies ist kein Konnektor für ein TikTok-Inhaltskonto.",
      description_ru: "Авторизуйте магазин с помощью собственного приложения продавца TikTok Shop, читайте товары, заказы и склады и обновляйте цены и запасы с подтверждением. Это не коннектор аккаунта для публикации контента TikTok.",
      description_it: "Autorizza il tuo negozio usando un'app TikTok Shop di proprietà del venditore, leggi prodotti, ordini e magazzini e aggiorna prezzi e scorte previa conferma. Questo non è un connettore per account TikTok dedicati ai contenuti.",
      description_ja: "販売者自身の TikTok Shop アプリで店舗を認証し、商品、注文、倉庫を参照して、確認後に価格と在庫を更新します。TikTok コンテンツアカウント向けの接続ではありません。",
      description_pt: "Autorize sua loja com um app próprio TikTok Shop, consulte produtos, pedidos e depósitos e atualize preços e estoque mediante confirmação. Não é um conector para contas de conteúdo TikTok.",
      auth_mode: 'local_api', local_api: { provider: 'tiktok_shop' },
      connection_setup: {
        callback_url: LOCAL_API_REDIRECT_URI,
        callback_help_zh: '将此地址完整复制到 Partner Center 中自有应用的 Redirect URL 配置；授权后自动返回 Orkas。',
        callback_help_en: 'Copy this exact address into your app’s Redirect URL setting in Partner Center. Authorization returns to Orkas automatically.',
        callback_help_es: "Copia esta dirección exacta en la configuración de Redirect URL de tu aplicación en Partner Center. Tras la autorización, volverás a Orkas automáticamente.",
        callback_help_fr: "Copiez cette adresse exacte dans le paramètre Redirect URL de votre application dans Partner Center. L’autorisation revient automatiquement à Orkas.",
        callback_help_ko: "이 주소를 그대로 Partner Center의 앱 Redirect URL 설정에 복사하세요. 승인 후 자동으로 Orkas로 돌아옵니다.",
        callback_help_de: "Kopieren Sie genau diese Adresse in die Redirect URL-Einstellung Ihrer App im Partner Center. Die Autorisierung führt automatisch zu Orkas zurück.",
        callback_help_ru: "Скопируйте именно этот адрес в настройку Redirect URL приложения в Partner Center. После авторизации вы автоматически вернётесь в Orkas.",
        callback_help_it: "Copia questo indirizzo esatto nell'impostazione Redirect URL della tua app in Partner Center. Al termine dell'autorizzazione tornerai automaticamente a Orkas.",
        callback_help_ja: "このアドレスをそのまま Partner Center のアプリの Redirect URL にコピーしてください。認証後は自動的に Orkas に戻ります。",
        callback_help_pt: "Copie este endereço exato para Redirect URL do app no Partner Center. A autorização retorna ao Orkas automaticamente.",
        requirement: 'provider_application',
        instructions_zh: '需要已通过卖家开发者审核的 Custom App；入口未开放请联系平台客户经理。启用 seller.product.basic、seller.product.write、seller.order.info、seller.logistics 权限，仅可连接应用获批的店铺和市场。',
        instructions_en: 'Requires a Custom App approved for seller development; contact your account manager if access is unavailable. Enable seller.product.basic, seller.product.write, seller.order.info and seller.logistics. Only approved shops and markets can connect.',
        instructions_es: "Requiere una Custom App aprobada para el desarrollo de vendedores; contacta con tu responsable de cuenta si el acceso no está disponible. Habilita seller.product.basic, seller.product.write, seller.order.info y seller.logistics. Solo pueden conectarse las tiendas y los mercados aprobados.",
        instructions_fr: "Nécessite une Custom App approuvée pour le développement vendeur ; contactez votre responsable de compte si l’accès n’est pas disponible. Activez seller.product.basic, seller.product.write, seller.order.info et seller.logistics. Seules les boutiques et les marchés approuvés peuvent se connecter.",
        instructions_ko: "판매자 개발용으로 승인된 Custom App이 필요합니다. 접근할 수 없다면 계정 담당자에게 문의하세요. seller.product.basic, seller.product.write, seller.order.info, seller.logistics를 활성화하세요. 승인된 상점과 시장만 연결할 수 있습니다.",
        instructions_de: "Erfordert eine für Verkäuferentwicklung genehmigte Custom App; wenden Sie sich an Ihren Kundenbetreuer, wenn der Zugriff nicht verfügbar ist. Aktivieren Sie seller.product.basic, seller.product.write, seller.order.info und seller.logistics. Nur genehmigte Shops und Märkte können verbunden werden.",
        instructions_ru: "Нужно Custom App, одобренное для разработки продавцом; если доступа нет, обратитесь к менеджеру аккаунта. Включите seller.product.basic, seller.product.write, seller.order.info и seller.logistics. Подключаться могут только одобренные магазины и рынки.",
        instructions_it: "Richiede una Custom App approvata per lo sviluppo da parte dei venditori; contatta il tuo referente commerciale se l'accesso non è disponibile. Abilita seller.product.basic, seller.product.write, seller.order.info e seller.logistics. Possono collegarsi solo negozi e mercati approvati.",
        instructions_ja: "販売者開発用に承認された Custom App が必要です。利用できない場合は担当マネージャーにお問い合わせください。seller.product.basic、seller.product.write、seller.order.info、seller.logistics を有効にしてください。承認済みの店舗と市場のみ接続できます。",
        instructions_pt: "Exige um Custom App aprovado para desenvolvimento por vendedores; contate seu gerente de conta se não tiver acesso. Habilite seller.product.basic, seller.product.write, seller.order.info e seller.logistics. Apenas lojas e mercados aprovados podem conectar.",
        guide_url: 'https://partner.tiktokshop.com/docv2/page/seller-developer-onboarding-onepager',
        guide_label_zh: '查看 TikTok Shop 官方卖家开发者指南', guide_label_en: 'Open the official TikTok Shop seller developer guide',
        guide_label_es: "Abrir la guía oficial de desarrollo para vendedores de TikTok Shop",
        guide_label_fr: "Ouvrir le guide officiel des développeurs vendeurs TikTok Shop",
        guide_label_ko: "TikTok Shop 판매자 공식 개발자 가이드 열기",
        guide_label_de: "Offiziellen Entwicklerleitfaden für TikTok Shop-Verkäufer öffnen",
        guide_label_ru: "Открыть официальное руководство разработчика для продавцов TikTok Shop",
        guide_label_it: "Apri la guida ufficiale di TikTok Shop per gli sviluppatori dei venditori", guide_label_ja: "TikTok Shop 公式販売者開発ガイドを開く", guide_label_pt: "Abrir guia oficial de desenvolvimento para vendedores TikTok Shop",
        fields: [
          { key: 'region', input: 'choice', storage: 'metadata', required: true, format: 'tiktok_shop_region', label_zh: '店铺授权市场', label_en: 'Shop authorization market',
          label_es: "Mercado de autorización de la tienda",
          label_fr: "Marché d’autorisation de la boutique",
          label_ko: "상점 승인 시장",
          label_de: "Autorisierungsmarkt des Shops",
          label_ru: "Рынок авторизации магазина",
          label_it: "Mercato di autorizzazione del negozio", label_ja: "店舗の認証市場", label_pt: "Mercado de autorização da loja",
            help_zh: '美国店铺使用美国授权入口，其余市场使用全球入口；与显示语言无关。', help_en: 'US shops use the US authorization entry; other markets use the global entry, regardless of display language.',
            help_es: "Las tiendas de Estados Unidos usan el acceso de autorización de Estados Unidos; los demás mercados usan el acceso global, independientemente del idioma de visualización.",
            help_fr: "Les boutiques américaines utilisent le point d’entrée d’autorisation US ; les autres marchés utilisent le point d’entrée mondial, indépendamment de la langue d’affichage.",
            help_ko: "표시 언어와 관계없이 미국 상점은 미국 승인 페이지를, 그 외 시장은 글로벌 승인 페이지를 사용합니다.",
            help_de: "US-Shops verwenden den US-Autorisierungszugang; andere Märkte verwenden den globalen Zugang, unabhängig von der Anzeigesprache.",
            help_ru: "Магазины США используют американскую страницу авторизации; остальные рынки — глобальную, независимо от языка интерфейса.",
            help_it: "I negozi degli Stati Uniti usano il punto di accesso all'autorizzazione per gli Stati Uniti; gli altri mercati usano quello globale, indipendentemente dalla lingua di visualizzazione.", help_ja: "表示言語に関係なく、米国の店舗は米国向け認証ページ、それ以外はグローバル向けページを使用します。", help_pt: "Lojas dos EUA usam a entrada de autorização dos EUA; os demais mercados usam a global, independentemente do idioma da interface.",
            options: [{ value: 'row', label_zh: '美国以外市场', label_en: 'Outside the United States',
            label_es: "Fuera de Estados Unidos",
            label_fr: "Hors des États-Unis",
            label_ko: "미국 외 지역",
            label_de: "Außerhalb der Vereinigten Staaten",
            label_ru: "За пределами США",
            label_it: "Al di fuori degli Stati Uniti", label_ja: "米国以外", label_pt: "Fora dos Estados Unidos" }, { value: 'us', label_zh: '美国', label_en: 'United States',
label_es: "Estados Unidos",
label_fr: "États-Unis",
label_ko: "미국",
label_de: "Vereinigte Staaten",
label_ru: "США",
label_it: "Stati Uniti", label_ja: "米国", label_pt: "Estados Unidos" }] },
          { key: 'shop_id', input: 'text', storage: 'metadata', required: true, format: 'tiktok_shop_code', label_zh: '店铺代码 / Shop ID', label_en: 'Shop code / Shop ID',
          label_es: "Código de tienda / Shop ID",
          label_fr: "Code de boutique / ID de boutique",
          label_ko: "상점 코드 / Shop ID",
          label_de: "Shopcode / Shop-ID",
          label_ru: "Код магазина / Shop ID",
          label_it: "Shop code / Shop ID", label_ja: "ショップコード / ショップ ID", label_pt: "Código da loja / Shop ID",
            help_zh: '从 Seller Center 的店铺资料复制店铺代码，或填写已知的 API Shop ID。授权后会精确匹配该店铺；无需填写 shop_cipher。', help_en: 'Copy the shop code from your Seller Center shop profile, or enter a known API Shop ID. Orkas matches it after authorization; you do not need shop_cipher.',
            help_es: "Copia el código de tienda del perfil de tu tienda en Seller Center o introduce un Shop ID de la API que conozcas. Orkas lo identifica tras la autorización; no necesitas shop_cipher.",
            help_fr: "Copiez le code de boutique depuis votre profil de boutique dans Seller Center, ou saisissez un Shop ID API connu. Orkas l’associe après l’autorisation ; vous n’avez pas besoin de shop_cipher.",
            help_ko: "Seller Center의 상점 프로필에서 상점 코드를 복사하거나 알고 있는 API Shop ID를 입력하세요. Orkas가 승인 후 일치 여부를 확인하므로 shop_cipher는 필요하지 않습니다.",
            help_de: "Kopieren Sie den Shopcode aus Ihrem Shopprofil im Seller Center oder geben Sie eine bekannte API-Shop ID ein. Orkas ordnet ihn nach der Autorisierung zu; Sie benötigen keinen shop_cipher.",
            help_ru: "Скопируйте код магазина из профиля магазина в Seller Center или введите известный API Shop ID. Orkas сопоставит его после авторизации; shop_cipher не нужен.",
            help_it: "Copia il codice del negozio dal profilo del negozio in Seller Center oppure inserisci uno Shop ID API noto. Orkas lo associa dopo l'autorizzazione; non serve shop_cipher.", help_ja: "Seller Center の店舗プロフィールからショップコードをコピーするか、既知の API Shop ID を入力してください。認証後に Orkas が照合します。shop_cipher は不要です。", help_pt: "Copie o código da loja no perfil do Seller Center ou informe um Shop ID conhecido da API. Orkas faz a correspondência após a autorização; não é necessário shop_cipher." },
          { key: 'service_id', input: 'text', storage: 'credential', required: true, format: 'tiktok_service_id', label_zh: 'Service ID', label_en: 'Service ID',
          label_es: "Service ID",
          label_fr: "ID du service",
          label_ko: "Service ID",
          label_de: "Service-ID",
          label_ru: "Service ID",
          label_it: "Service ID", label_ja: "Service ID", label_pt: "Service ID",
            help_zh: '来自 Partner Center > App & Service > 应用详情，或“Copy authorization link”链接中的 service_id；不是 App Key。', help_en: 'Find it in Partner Center > App & Service > app details, or the service_id in Copy authorization link. It is not the App Key.',
            help_es: "Encuéntralo en Partner Center > App & Service > app details, o como service_id en Copy authorization link. No es la App Key.",
            help_fr: "Trouvez-le dans Partner Center > App & Service > détails de l’application, ou dans service_id de Copy authorization link. Il ne s’agit pas de l’App Key.",
            help_ko: "Partner Center > App & Service > 앱 상세 정보 또는 Copy authorization link의 service_id에서 확인하세요. App Key가 아닙니다.",
            help_de: "Sie finden ihn unter Partner Center > App & Service > App-Details oder als service_id in Copy authorization link. Er ist nicht der App Key.",
            help_ru: "Найдите в Partner Center > App & Service > сведения о приложении или в параметре service_id ссылки Copy authorization link. Это не App Key.",
            help_it: "Lo trovi in Partner Center > App & Service > app details oppure come service_id in Copy authorization link. Non è l'App Key.", help_ja: "Partner Center > App & Service > アプリの詳細、または Copy authorization link 内の service_id から取得してください。App Key とは異なります。", help_pt: "Encontre em Partner Center > App & Service > detalhes do app ou em service_id no link de Copy authorization link. Não é a App Key." },
          { key: 'app_key', input: 'text', storage: 'credential', required: true, format: 'app_key', label_zh: 'App Key', label_en: 'App Key',
          label_es: "Clave de aplicación",
          label_fr: "App Key",
          label_ko: "App Key",
          label_de: "App Key",
          label_ru: "App Key",
          label_it: "App Key", label_ja: "App Key", label_pt: "App Key",
            help_zh: '在同一自有应用详情页复制 App Key，不要使用 TikTok for Developers 内容应用的 Client Key。', help_en: 'Copy the App Key from that seller-owned app, not a TikTok for Developers content-app Client Key.',
            help_es: "Copia la App Key de esa aplicación propiedad del vendedor, no la Client Key de una aplicación de contenido de TikTok for Developers.",
            help_fr: "Copiez l’App Key de cette application appartenant au vendeur, et non une Client Key d’application de contenu TikTok for Developers.",
            help_ko: "해당 판매자 소유 앱에서 App Key를 복사하세요. TikTok for Developers 콘텐츠 앱의 Client Key가 아닙니다.",
            help_de: "Kopieren Sie den App Key dieser eigenen Verkäufer-App, keinen Client Key einer Inhalts-App von TikTok for Developers.",
            help_ru: "Скопируйте App Key из этого собственного приложения продавца, а не Client Key контентного приложения TikTok for Developers.",
            help_it: "Copia l'App Key da quell'app di proprietà del venditore, non il Client Key di un'app per contenuti di TikTok for Developers.", help_ja: "販売者所有のアプリの App Key をコピーしてください。TikTok for Developers のコンテンツアプリの Client Key ではありません。", help_pt: "Copie a App Key desse app próprio de vendedor, não a Client Key de um app de conteúdo TikTok for Developers." },
          { key: 'app_secret', input: 'secret', storage: 'credential', required: true, format: 'secret', label_zh: 'App Secret', label_en: 'App Secret',
          label_es: "Secreto de aplicación",
          label_fr: "App Secret",
          label_ko: "App Secret",
          label_de: "App Secret",
          label_ru: "App Secret",
          label_it: "App Secret", label_ja: "App Secret", label_pt: "App Secret",
            help_zh: '在同一应用详情页查看并复制 App Secret。', help_en: 'Reveal and copy the App Secret from the same app details page.',
            help_es: "Muestra y copia el App Secret de la misma página de detalles de la aplicación.",
            help_fr: "Affichez et copiez l’App Secret depuis la même page de détails de l’application.",
            help_ko: "같은 앱 상세 정보 페이지에서 App Secret을 표시한 후 복사하세요.",
            help_de: "Blenden Sie das App Secret auf derselben App-Detailseite ein und kopieren Sie es.",
            help_ru: "Покажите и скопируйте App Secret на той же странице сведений о приложении.",
            help_it: "Mostra e copia l'App Secret dalla stessa pagina dei dettagli dell'app.", help_ja: "同じアプリの詳細画面で App Secret を表示してコピーしてください。", help_pt: "Revele e copie o App Secret na mesma página de detalhes do app." },
        ],
      },
      allowed_tools: tools, tool_policies: toolPolicies, transport_template: transport,
    },
  ];
}
