import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {expect,it} from 'vitest';
const require=createRequire(import.meta.url),codec=require('../../../../bin/local-api-credential-codec.cjs');
it('runs Alibaba.com through the real six-tool host with full fields, fixed signing identity and durable risk boundaries',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orkas-icbu-journey-')),file=path.join(dir,'grant.enc'),key=crypto.randomBytes(32).toString('base64url'),preload=path.join(dir,'provider.cjs'),journal=path.join(dir,'wire.jsonl');
 const grant={provider:'alibaba_icbu',app_key:'fixture-app',app_secret:'fixture-private-secret',access_token:'fixture-private-access',expires_at:Date.now()+3600000,refresh_expires_at:Date.now()+7200000,identity:{account_id:'9007199254740993',app_fingerprint:crypto.createHash('sha256').update('fixture-app').digest('hex')}};codec.writeCredentialFile(file,key,grant);
 fs.writeFileSync(preload,`
 const fs=require('node:fs'),crypto=require('node:crypto');global.fetch=async(raw,init)=>{const u=new URL(raw),p=new URLSearchParams(init.body),m=p.get('method');if(u.href!=='https://eco.taobao.com/router/rest'||p.get('session')!=='fixture-private-access'||p.get('app_key')!=='fixture-app'||init.method!=='POST')throw Error('Unbound request');const expected=crypto.createHmac('md5','fixture-private-secret').update([...p.entries()].filter(([k])=>k!=='sign').sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>k+v).join('')).digest('hex').toUpperCase();if(p.get('sign')!==expected)throw Error('Bad signature');fs.appendFileSync(process.env.FIXTURE_JOURNAL,JSON.stringify({method:m,body:init.body})+'\\n');const reply=b=>new Response(JSON.stringify({[m.replaceAll('.','_')+'_response']:b}));
 if(m==='alibaba.icbu.product.list')return new Response('{"alibaba_icbu_product_list_response":{"total_item":1,"products":{"alibaba_product_brief_response":[{"product_id":"opaque","id":9007199254740993,"subject":"Fixture"}]}}}');
 if(m==='alibaba.seller.order.get')return reply({value:{trade_id:'9007199254740993',buyer:{phone:'0101',address:'Dock'},message:'Leave at reception'}});
 if(m==='alibaba.icbu.product.add.draft')return reply({product_id:'draft-1'});
 if(m==='alibaba.icbu.product.inventory.update'){if(!p.get('request_param').includes('"product_id":9007199254740993'))throw Error('Rounded ID');return reply({result:{success:false,msg_code:'STOCK_REJECTED',message:'private diagnostic'}});}
 if(m==='alibaba.icbu.photobank.group.operate')return reply({photo_group_result:{photobank_group:{id:3,name:'Photos'}}});throw Error('Unexpected request');};`);
 const clients:Client[]=[],stderr:string[]=[];async function connect(){const client=new Client({name:'icbu-merchant-journey',version:'1'});clients.push(client);const transport=new StdioClientTransport({command:process.execPath,args:['--require',preload,path.resolve(__dirname,'../../../../bin/direct-commerce-mcp-server.cjs')],stderr:'pipe',env:{...Object.fromEntries(Object.entries(process.env).filter((x):x is[string,string]=>typeof x[1]==='string')),ELECTRON_RUN_AS_NODE:'1',ORKAS_LOCAL_API_PROVIDER:'alibaba_icbu',ORKAS_LOCAL_API_CREDENTIAL_FILE:file,ORKAS_LOCAL_API_CREDENTIAL_KEY:key,ORKAS_LOCAL_API_METADATA_JSON:'{}',FIXTURE_JOURNAL:journal}});transport.stderr?.on('data',data=>stderr.push(String(data)));await client.connect(transport);return client;}
 const read=(r:any)=>JSON.parse(r.content[0].text);
 try{const client=await connect();expect((await client.listTools()).tools).toHaveLength(6);const directory=read(await client.callTool({name:'list_capabilities',arguments:{}}));expect(directory.actions).toHaveLength(72);expect(JSON.stringify(directory)).not.toContain('input_schema');expect(directory.actions.some((x:any)=>x.action==='alibaba.icbu.photobank.upload')).toBe(false);expect(read(await client.callTool({name:'describe_action',arguments:{action:'alibaba.icbu.product.add'}})).input_schema.properties.custom_info).toBeDefined();
 const product=await client.callTool({name:'execute_read',arguments:{action:'alibaba.icbu.product.list',parameters:{language:'ENGLISH',page_size:1}}});expect(product.isError).not.toBe(true);expect(read(product).result.data.alibaba_icbu_product_list_response.products.alibaba_product_brief_response[0].id).toBe('9007199254740993');
 const order=await client.callTool({name:'execute_read',arguments:{action:'orders.get',parameters:{order_id:'9007199254740993'}}});expect(read(order).result.data.buyer.address).toBe('Dock');
 const draft={action:'alibaba.icbu.product.add.draft',parameters:{category_id:1,language:'ENGLISH',product_type:'sourcing',subject:'Draft'}};expect((await client.callTool({name:'execute_read',arguments:draft})).isError).toBe(true);expect((await client.callTool({name:'execute_write',arguments:draft})).isError).not.toBe(true);await client.close();const restarted=await connect();
 const stock={action:'alibaba.icbu.product.inventory.update',parameters:{request_param:{product_id:'9007199254740993',inventory_list:[{sku_id:2,inventory_code:'CN_LOCAL_01',inventory:1,operate:'plus'}]}}};expect((await restarted.callTool({name:'execute_write',arguments:stock})).isError).toBe(true);const partial=await restarted.callTool({name:'execute_high_impact',arguments:stock});expect(partial.isError).toBe(true);expect(read(partial).result.status).toBe('partial_or_failed');expect(JSON.stringify(partial)).not.toContain('private diagnostic');
 const remove={action:'alibaba.icbu.photobank.group.operate',parameters:{photo_group_operation_request:{operation:'delete',group_id:3}}};expect((await restarted.callTool({name:'execute_high_impact',arguments:remove})).isError).toBe(true);expect((await restarted.callTool({name:'execute_destructive',arguments:remove})).isError).not.toBe(true);
 const calls=fs.readFileSync(journal,'utf8').trim().split('\n').map(line=>JSON.parse(line).method);expect(calls.filter((x:string)=>x!=='alibaba.icbu.product.list')).toEqual(['alibaba.seller.order.get','alibaba.icbu.product.add.draft','alibaba.icbu.product.inventory.update','alibaba.icbu.photobank.group.operate']);expect(codec.readCredentialFile(file,key)).toEqual(grant);expect(stderr).toEqual([]);expect(JSON.stringify([product,order,partial])).not.toContain('fixture-private-access');
 }finally{await Promise.allSettled(clients.map(c=>c.close()));fs.rmSync(dir,{recursive:true,force:true});}
},20000);
