import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {expect,it} from 'vitest';
const require=createRequire(import.meta.url),codec=require('../../../../bin/local-api-credential-codec.cjs');
it('runs the current seven-scope merchant over real six-tool MCP with complete fields and risk boundaries',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orkas-kuaishou-journey-')),file=path.join(dir,'grant.enc'),key=crypto.randomBytes(32).toString('base64url'),preload=path.join(dir,'provider.cjs'),journal=path.join(dir,'wire.jsonl');
 const grant={provider:'kuaishou_shop',app_key:'fixture-app-key',app_secret:'fixture-app-private',sign_secret:'fixture-sign-private',access_token:'fixture-access-private',refresh_token:'fixture-refresh-private',scope:'user_base user_info merchant_user merchant_item merchant_order merchant_refund merchant_logistics',expires_at:Date.now()+3600000,refresh_expires_at:Date.now()+86400000,identity:{shop_id:'9007199254740993',open_id:'merchant-open-id'}};codec.writeCredentialFile(file,key,grant);
 fs.writeFileSync(preload,`
 const fs=require('node:fs'),crypto=require('node:crypto');global.fetch=async(raw,init)=>{const u=new URL(raw),q=Object.fromEntries(init.method==='POST'?new URLSearchParams(init.body):u.searchParams),p=JSON.parse(q.param),actual=q.sign;delete q.sign;if(u.origin!=='https://openapi.kwaixiaodian.com'||q.appkey!=='fixture-app-key'||q.access_token!=='fixture-access-private')throw Error('Unbound request');const text=Object.keys(q).sort().map(k=>k+'='+q[k]).join('&')+'&signSecret=fixture-sign-private';if(actual!==crypto.createHmac('sha256','fixture-sign-private').update(text).digest('hex'))throw Error('Bad signature');fs.appendFileSync(process.env.FIXTURE_JOURNAL,JSON.stringify({method:q.method,params:p})+'\\n');const reply=data=>new Response(JSON.stringify({result:1,msg:'success',...(data===undefined?{}:{data})}));
 if(q.method==='open.user.seller.get')return new Response('{"result":1,"data":{"sellerId":9007199254740993,"openId":"merchant-open-id","name":"Merchant"}}');
 if(q.method==='open.shop.info.get')return reply({shopName:'Shop',shopType:6});
 if(q.method==='open.order.detail'){if(!q.param.includes('"oid":9007199254740993'))throw Error('Rounded order ID');return reply({orderAddress:{encryptedAddress:'cipher',desensitiseAddress:'Dock'},buyer_message:'Leave at reception'});}
 if(q.method==='open.seller.order.note.add'){if(p.note!=='Packed')throw Error('Lost note');return reply();}
 if(q.method==='open.item.shelf.status.update')return reply();
 if(q.method==='open.member.batch.update.level')return new Response(JSON.stringify({result:1,updateResultList:[{openId:'buyer-a',result:true},{openId:'buyer-b',result:false,failReason:'private diagnostic'}]}));
 if(q.method==='open.item.delete')return reply();throw Error('Unexpected request');};`);
 const clients:Client[]=[],stderr:string[]=[];async function connect(){const client=new Client({name:'kuaishou-merchant-journey',version:'1'});clients.push(client);const transport=new StdioClientTransport({command:process.execPath,args:['--require',preload,path.resolve(__dirname,'../../../../bin/direct-commerce-mcp-server.cjs')],stderr:'pipe',env:{...Object.fromEntries(Object.entries(process.env).filter((x):x is [string,string]=>typeof x[1]==='string')),ELECTRON_RUN_AS_NODE:'1',ORKAS_LOCAL_API_PROVIDER:'kuaishou_shop',ORKAS_LOCAL_API_CREDENTIAL_FILE:file,ORKAS_LOCAL_API_CREDENTIAL_KEY:key,ORKAS_LOCAL_API_METADATA_JSON:'{}',FIXTURE_JOURNAL:journal}});transport.stderr?.on('data',data=>stderr.push(String(data)));await client.connect(transport);return client;}
 const read=(r:any)=>JSON.parse(r.content[0].text);
 try{const client=await connect();expect((await client.listTools()).tools).toHaveLength(6);const directory=read(await client.callTool({name:'list_capabilities',arguments:{}}));expect(directory.actions).toHaveLength(159);expect(JSON.stringify(directory)).not.toContain('input_schema');expect(directory.actions.some((x:any)=>x.action==='open.promotion.coupon.create')).toBe(false);const described=read(await client.callTool({name:'describe_action',arguments:{action:'open.item.new'}}));expect(described.input_schema.properties.itemVideo).toBeDefined();
 expect(directory.actions.find((x:any)=>x.action==='open.express.ebill.get').risk).toBe('H');expect((await client.callTool({name:'execute_read',arguments:{action:'open.express.ebill.get',parameters:{getEbillOrderRequest:[]}}})).isError).toBe(true);
 const order=await client.callTool({name:'execute_read',arguments:{action:'open.order.detail',parameters:{oid:'9007199254740993'}}});expect(order.isError).not.toBe(true);expect(read(order).result.data.data.orderAddress.desensitiseAddress).toBe('Dock');
 const note={action:'open.seller.order.note.add',parameters:{orderId:1,note:'Packed'}};expect((await client.callTool({name:'execute_read',arguments:note})).isError).toBe(true);expect((await client.callTool({name:'execute_write',arguments:note})).isError).not.toBe(true);
 const publish={action:'open.item.shelf.status.update',parameters:{kwaiItemId:1,shelfStatus:1}};expect((await client.callTool({name:'execute_write',arguments:publish})).isError).toBe(true);expect((await client.callTool({name:'execute_high_impact',arguments:publish})).isError).not.toBe(true);await client.close();const restarted=await connect();
 const partial=await restarted.callTool({name:'execute_high_impact',arguments:{action:'open.member.batch.update.level',parameters:{levelChangeInfo:[{openId:'buyer-a',level:1,version:1},{openId:'buyer-b',level:2,version:1}]}}});expect(partial.isError).toBe(true);expect(read(partial).result.status).toBe('partial_or_failed');expect(JSON.stringify(partial)).not.toContain('private diagnostic');
 const remove={action:'open.item.delete',parameters:{kwaiItemId:1}};expect((await restarted.callTool({name:'execute_high_impact',arguments:remove})).isError).toBe(true);expect((await restarted.callTool({name:'execute_destructive',arguments:remove})).isError).not.toBe(true);
 const calls=fs.readFileSync(journal,'utf8').trim().split('\n').map(line=>JSON.parse(line).method);expect(calls.filter((x:string)=>!['open.user.seller.get','open.shop.info.get'].includes(x))).toEqual(['open.order.detail','open.seller.order.note.add','open.item.shelf.status.update','open.member.batch.update.level','open.item.delete']);expect(calls.filter((x:string)=>x==='open.user.seller.get').length).toBeGreaterThan(0);expect(codec.readCredentialFile(file,key)).toEqual(grant);expect(stderr).toEqual([]);expect(JSON.stringify([order,partial])).not.toContain('fixture-access-private');
 }finally{await Promise.allSettled(clients.map(c=>c.close()));fs.rmSync(dir,{recursive:true,force:true});}
},20000);
