import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {expect,it} from 'vitest';
const require=createRequire(import.meta.url),codec=require('../../../../bin/local-api-credential-codec.cjs');
it('preserves complete Magento fulfilment through the real bound MCP runtime and restart',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orkas-magento-full-')),file=path.join(dir,'grant.enc'),key=crypto.randomBytes(32).toString('base64url'),preload=path.join(dir,'provider.cjs');
 const binding='https://shop.example.com/magento',stores=[{id:1,code:'default',website_id:1,currency:'USD'}],fingerprint=crypto.createHash('sha256').update(JSON.stringify([{id:1,code:'default',website_id:1}])).digest('hex');
 codec.writeCredentialFile(file,key,{provider:'magento',consumer_key:'consumer-fixture',consumer_secret:'consumer-secret-fixture',access_token:'access-token-fixture',token_secret:'token-secret-fixture',identity:{binding,stores,fingerprint}});
 fs.writeFileSync(preload,`
 const dns=require('node:dns').promises;dns.lookup=async()=>[{address:'93.184.216.34',family:4}];global.fetch=async(raw,init)=>{const url=new URL(String(raw));if(url.origin!=='https://shop.example.com'||!url.pathname.startsWith('/magento/rest/V1/')||init.method!=='GET'||init.redirect!=='error'||!init.headers.authorization.startsWith('OAuth '))throw Error('Wrong bound request');
 if(url.pathname.endsWith('/store/storeConfigs'))return new Response(JSON.stringify([{id:1,code:'default',website_id:1,base_currency_code:'USD',locale:'en_US',timezone:'UTC',secure_base_url:'https://shop.example.com/magento/'}]));
 if(url.pathname.endsWith('/orders/21'))return new Response('{"entity_id":21,"grand_total":49.25,"customer_email":"buyer@example.com","billing_address":{"firstname":"Fixture","street":["Fixture road"],"telephone":"1234567"},"payment":{"method":"checkmo","amount_ordered":49.25,"access_token":"private"},"extension_attributes":{"external_order_id":9007199254740993},"status_histories":[{"comment":"Keep note"}]}');
 if(url.pathname.endsWith('/inventory/sources'))return new Response(JSON.stringify({items:[{source_code:'default',email:'warehouse@example.com',phone:'1234567',street:'Warehouse road'}],total_count:1}));
 throw Error('Unexpected route');};`);
 const clients:Client[]=[],stderr:string[]=[];const result=(r:any)=>JSON.parse(r.content[0].text);
 const connect=async()=>{const c=new Client({name:'magento-fullfields',version:'1'});clients.push(c);const t=new StdioClientTransport({command:process.execPath,args:['--require',preload,path.resolve(__dirname,'../../../../bin/direct-commerce-mcp-server.cjs')],stderr:'pipe',env:{...Object.fromEntries(Object.entries(process.env).filter((x):x is[string,string]=>typeof x[1]==='string')),ELECTRON_RUN_AS_NODE:'1',ORKAS_LOCAL_API_PROVIDER:'magento',ORKAS_LOCAL_API_METADATA_JSON:JSON.stringify({store_url:binding}),ORKAS_LOCAL_API_CREDENTIAL_FILE:file,ORKAS_LOCAL_API_CREDENTIAL_KEY:key}});t.stderr?.on('data',x=>stderr.push(String(x)));await c.connect(t);return c;};
 try{const c=await connect();expect((await c.listTools()).tools).toHaveLength(6);expect(result(await c.callTool({name:'list_capabilities',arguments:{}})).actions).toHaveLength(9);const query={action:'orders.get',parameters:{order_id:21}};expect((await c.callTool({name:'execute_high_impact',arguments:query})).isError).toBe(true);const read=await c.callTool({name:'execute_read',arguments:query});expect(read.isError).not.toBe(true);expect(result(read).result.data).toMatchObject({grand_total:49.25,customer_email:'buyer@example.com',billing_address:{street:['Fixture road']},payment:{method:'checkmo',amount_ordered:49.25},extension_attributes:{external_order_id:'9007199254740993'},status_histories:[{comment:'Keep note'}]});expect(result(read).result.data.payment).not.toHaveProperty('access_token');const shop=result(await c.callTool({name:'execute_read',arguments:{action:'shop.get',parameters:{}}}));expect(shop.result.data[0]).toMatchObject({locale:'en_US',timezone:'UTC'});await c.close();const resumed=await connect(),source=await resumed.callTool({name:'execute_read',arguments:{action:'sources.list',parameters:{}}});expect(source.isError).not.toBe(true);expect(result(source).result.data.items[0]).toMatchObject({email:'warehouse@example.com',phone:'1234567',street:'Warehouse road'});expect(stderr).toEqual([]);expect(fs.readFileSync(file,'utf8')).not.toContain('access-token-fixture');}finally{await Promise.allSettled(clients.map(c=>c.close()));fs.rmSync(dir,{recursive:true,force:true});}
},15000);
