import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import {afterEach,describe,expect,it,vi} from 'vitest';
const require=createRequire(import.meta.url),api=require('../../../../bin/qoo10-business-api.cjs'),{AjvJsonSchemaValidator}=require('@modelcontextprotocol/sdk/validation/ajv'),{withRequestSignal}=require('../../../../bin/commerce-request-context.cjs');
const KEY='fixture-qoo10-certification',config=()=>({provider:'qoo10_japan',metadata:{},credentials:{provider:'qoo10_japan',certification_key:KEY,identity:{key_fingerprint:crypto.createHash('sha256').update(KEY).digest('hex')}}});
const reply=(ResultObject?:unknown,ResultCode=0)=>new Response(JSON.stringify({ResultObject,ResultCode,ResultMsg:KEY}));
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();});
// Oracles use the public guide's parameter tables, protocol examples and result
// codes, rather than treating an HTTP 200 or a synthetic success label as state.
describe('Qoo10 complete merchant contracts',()=>{
 it('keeps full per-action fields out of the compact directory and scopes irreversible operations separately',()=>{
  const actions=api.actionsFor(),v=new AjvJsonSchemaValidator();expect(Object.keys(actions)).toHaveLength(58);for(const row of Object.values(actions) as any[])expect(()=>v.getValidator(row.input_schema)).not.toThrow();
  expect(actions['CertificationAPI.CreateCertificationKey']).toBeUndefined();expect(actions['Claim.SetCancelProcess'].risk).toBe('D');expect(actions['CSCenter.SetInquiryMessage'].risk).toBe('H');expect(actions['ItemsContents.EditGoodsContents'].risk).toBe('H');expect(actions['ItemsContents.EditGoodsHeaderFooter'].risk).toBe('H');expect(actions['ItemsLookup.RequestFileDownload'].risk).toBe('H');
  expect(actions['ItemsBasic.SetNewGoods'].input_schema.properties).toHaveProperty('ContactInfo');expect(actions['ItemsContents.EditGoodsMultiImage'].input_schema.properties).toHaveProperty('EnlargedImage50');expect(actions['ItemsBasic.UpdateMoveGoods'].input_schema.properties.OptionQty.type).toBe('string');
  expect(JSON.stringify(Object.values(actions).map((x:any)=>x.description))).not.toContain('AvailableDateValue');
 });
 it('creates a full product with source-specific versions, Japanese contents and contact information intact',async()=>{
  const fetch=vi.fn().mockResolvedValue(reply({GdNo:'1234567890',BIContentsNo:null,AIContentsNo:null,optionImgResult:[],InventoryImgResult:[]}));vi.stubGlobal('fetch',fetch);
  const input={SecondSubCat:'300000001',ItemTitle:'綿シャツ',ItemPrice:1000,ItemQty:0,AvailableDateType:'0',AvailableDateValue:'3',ContactInfo:'buyer-support@example.invalid',ItemDescription:'<p>綿100%</p>',StandardImage:'https://merchant.example.invalid/image.jpg',ItemType:'色||*青||*0||*10||*BLUE',TaxRate:'10'};
  const result=await api.execute(config(),'ItemsBasic.SetNewGoods',input);expect(result.status).toBe('acknowledged');expect(result.data.ResultObject.GdNo).toBe('1234567890');expect(result.data.ResultMsg).toBeUndefined();
  const [url,init]=fetch.mock.calls[0];expect(url).toBe('https://api.qoo10.jp/GMKT.INC.Front.QAPIService/ebayjapan.qapi/ItemsBasic.SetNewGoods');expect(init.headers).toMatchObject({GiosisCertificationKey:KEY,QAPIVersion:'1.1'});expect(Object.fromEntries(new URLSearchParams(init.body))).toMatchObject({...input,ItemPrice:'1000',ItemQty:'0'});expect(url).not.toContain(KEY);expect(fetch).toHaveBeenCalledOnce();
 });
 it('supports the official MOVE delimiter example and code enums while enforcing byte-counted content limits',async()=>{
  const fetch=vi.fn().mockResolvedValue(reply());vi.stubGlobal('fetch',fetch);
  const image='https://merchant.example.invalid/'+('a'.repeat(100))+'.jpg',p={ItemCode:'1234567890',SecondSubCat:'320001873',ItemPrice:1000,OptionType:'Black||*#000000||*Y$$White||*#FFFFFF||*N',OptionMainimage:'Black||*'+image+'$$White||*'+image,OptionQty:'Black||*S||*20||*BLACK-S',StyleNumber:'STY0001',TpoNumber:'TPO0001',SeasonType:'1$$3',ShippingNo:123456,AvailableDateValue:'3',OriginType:'1',ExpireDate:'2027-01-01',IndustrialCodeType:'JAN',ItemSeriesName:'1234567890123456'};
  expect((await api.execute(config(),'ItemsBasic.UpdateMoveGoods',p)).status).toBe('accepted');expect(new URLSearchParams(fetch.mock.calls[0][1].body).get('OptionMainimage')).toBe(p.OptionMainimage);
  await expect(api.execute(config(),'ItemsBasic.UpdateMoveGoods',{...p,ItemDescription:'綿'.repeat(600)})).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(fetch).toHaveBeenCalledOnce();
 });
 it('retains complete fulfillment, customer and settlement fields, pagination and exact 64-bit content IDs',async()=>{
  const orders=[{OrderNo:1062428737,Receiver:'Buyer',BuyerEmail:'buyer@example.invalid',ShippingAddress:'Example Street',ShippingMessage:'Leave at desk',PaymentMethod:'Card',Total:1e20}],fetch=vi.fn().mockResolvedValueOnce(reply(orders)).mockResolvedValueOnce(reply({TotalItems:501,TotalPages:2,PresentPage:1,Items:[{ItemCode:'1234567890',SellerCode:'SKU'}]})).mockResolvedValueOnce(new Response('{"ResultCode":0,"ResultObject":{"GdNo":"1234567890","BIContentsNo":9223372036854775807,"AIContentsNo":null}}'));
  vi.stubGlobal('fetch',fetch);expect((await api.execute(config(),'ShippingBasic.GetShippingInfo_v3',{ShippingStatus:'4',SearchStartDate:'20261001',SearchEndDate:'20261001235959'})).data.ResultObject).toEqual(orders);expect((await api.execute(config(),'ItemsLookup.GetAllGoodsInfo',{ItemStatus:'S2'})).data.ResultObject.TotalPages).toBe(2);expect(new URLSearchParams(fetch.mock.calls[1][1].body).get('Page')).toBe('1');
  const result=await api.execute(config(),'ItemsBasic.SetNewGoods',{SecondSubCat:'300000001',ItemTitle:'Linen',ItemPrice:1000,ItemQty:1,AvailableDateType:'0',AvailableDateValue:'3'});expect(result.data.ResultObject.BIContentsNo).toBe('9223372036854775807');
 });
 it('preserves exact unknown IDs, bounds nested results and strips credential XML while keeping merchant contact data',async()=>{
  const xml='<XmlDocument><ResultCode>0</ResultCode><ResultObject><Receiver>Buyer</Receiver><Password>not-the-token</Password><GiosisCertificationKey>'+KEY+'</GiosisCertificationKey></ResultObject></XmlDocument>',fetch=vi.fn().mockResolvedValueOnce(new Response('{"ResultCode":0,"ResultObject":[{"FutureID":9223372036854775807}]}')).mockResolvedValueOnce(new Response('{"ResultCode":0,"ResultObject":[{"FutureID":9.223372036854775807e18}]}')).mockResolvedValueOnce(new Response('{"ResultCode":0,"ResultObject":'+('['.repeat(50))+'0'+(']'.repeat(50))+'}')).mockResolvedValueOnce(new Response(xml));vi.stubGlobal('fetch',fetch);
  expect((await api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).data.ResultObject[0].FutureID).toBe('9223372036854775807');for(let i=0;i<2;i++)await expect(api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
  const result=await api.execute(config(),'ShippingBasic.GetSellingReportDetailList',{SearchCondition:'1',Search_Sdate:'2026-10-01',Search_Edate:'2026-10-01',Currency:'JPY'});expect(result.data).toContain('<Receiver>Buyer</Receiver>');expect(result.data).not.toContain('not-the-token');expect(result.data).not.toContain(KEY);
 });
 it('correlates per-order shipping results after a partial batch and rejects missing, duplicated and foreign acknowledgements',async()=>{
  const rows=[{OrderNo:'1062428737',ShippingCorp:'ゆうパック',TrackingNo:'A123'},{OrderNo:'1062428738',ShippingCorp:'ゆうパック',TrackingNo:'A124'}],partial=[{contr_no:1062428737,result_cd:0},{contr_no:1062428738,result_cd:-10103}],fetch=vi.fn().mockResolvedValueOnce(reply(partial)).mockResolvedValueOnce(reply([partial[0]])).mockResolvedValueOnce(reply([partial[0],partial[0]])).mockResolvedValueOnce(reply([partial[0],{contr_no:9,result_cd:0}]));vi.stubGlobal('fetch',fetch);
  const result=await api.execute(config(),'ShippingBasic.SetSendingInfoBulk',{ShippingInfoJson:rows});expect(result.status).toBe('partial_or_failed');expect(result.data.ResultObject).toEqual(partial);expect(JSON.parse(new URLSearchParams(fetch.mock.calls[0][1].body).get('ShippingInfoJson')!)).toEqual(rows);
  for(let i=0;i<3;i++)await expect(api.execute(config(),'ShippingBasic.SetSendingInfoBulk',{ShippingInfoJson:rows})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});expect(fetch).toHaveBeenCalledTimes(4);
 });
 it('does not claim opaque inventory batches or response-undocumented MOVE writes are completed',async()=>{
  const fetch=vi.fn().mockResolvedValueOnce(reply([{ItemCode:'1234567890',ProviderBusinessResult:'unclassified'}])).mockResolvedValueOnce(reply(undefined));vi.stubGlobal('fetch',fetch);
  const result=await api.execute(config(),'ItemsOrder.SetGoodsPriceQtyBulk',{ItemInfoJson:[{ItemCode:'1234567890',Qty:'0',Price:'1000',TaxRate:'10'}]});expect(result.status).toBe('accepted');expect(result.follow_up).toContain('Verify each');expect(result.data.ResultObject[0].ProviderBusinessResult).toBe('unclassified');
  expect((await api.execute(config(),'ItemsBasic.EditMoveGoodsStatus',{ItemCode:'1234567890',Status:'2'})).status).toBe('accepted');expect(fetch).toHaveBeenCalledTimes(2);
 });
 it('treats partial image registration as incomplete and preserves explicit protocol-only mutation acknowledgements',async()=>{
  const fetch=vi.fn().mockResolvedValueOnce(reply({GdNo:'1234567890',optionImgResult:[{contentsNo:1,imageUrl:'https://merchant.example.invalid/a.jpg',isRegistered:false}]})).mockResolvedValueOnce(reply()).mockResolvedValueOnce(reply());vi.stubGlobal('fetch',fetch);
  expect((await api.execute(config(),'ItemsBasic.SetNewGoods',{SecondSubCat:'300000001',ItemTitle:'Linen',ItemPrice:1000,ItemQty:1,AvailableDateType:'0',AvailableDateValue:'3'})).status).toBe('partial_or_failed');expect((await api.execute(config(),'Claim.SetCancelProcess',{ContrNo:'1062428737',CancelReason:'3',SellerMemo:'Delay'})).status).toBe('acknowledged');
  await api.execute(config(),'ItemsOptions.UpdateInventoryQtyPlusUnit',{ItemCode:'1234567890',OptionName:'色',OptionValue:'青',OptionCode:'BLUE',PlusQty:-1});expect(new URLSearchParams(fetch.mock.calls[2][1].body).get('PlusQty')).toBe('-1');
 });
 it('keeps customer replies and export requests on the provider without following content or download URLs',async()=>{
  const fetch=vi.fn().mockResolvedValueOnce(reply({SEQ_NO:123})).mockResolvedValueOnce(reply([{DownloadURL:'https://merchant.example.invalid/file.csv',DownloadType:'order',DownloadExplain:'Ready'}]));vi.stubGlobal('fetch',fetch);
  const replyResult=await api.execute(config(),'CSCenter.SetInquiryMessage',{inq_type:'MSG',question_no:'123',seq_no:'1',contents:'発送予定日は明日です。'});expect(replyResult.status).toBe('acknowledged');expect(new URLSearchParams(fetch.mock.calls[0][1].body).get('contents')).toBe('発送予定日は明日です。');
  expect((await api.execute(config(),'ItemsLookup.RequestFileDownload',{apply_type:'order',email:'merchant@example.invalid'})).status).toBe('accepted');expect(fetch).toHaveBeenCalledTimes(2);expect(fetch.mock.calls.every(([url])=>new URL(url).host==='api.qoo10.jp')).toBe(true);
 });
 it('returns bounded inert XML settlement reports and rejects placeholders, business errors and entity documents',async()=>{
  const xml='<?xml version="1.0"?><XmlDocument><ResultCode>0</ResultCode><ResultObject><Order><OrderNo>1062428737</OrderNo><SettlePrice>900</SettlePrice></Order></ResultObject></XmlDocument>',fetch=vi.fn().mockResolvedValueOnce(new Response(xml)).mockResolvedValueOnce(new Response('<XmlDocument><ResultCode>0</ResultCode><ResultObject>XmlOnly</ResultObject></XmlDocument>')).mockResolvedValueOnce(new Response('<XmlDocument><ResultCode>999</ResultCode><ResultMsg>secret</ResultMsg></XmlDocument>')).mockResolvedValueOnce(new Response('<!DOCTYPE doc [<!ENTITY x SYSTEM "file:///etc/passwd">]><XmlDocument><ResultCode>0</ResultCode></XmlDocument>'));vi.stubGlobal('fetch',fetch);
  const p={SearchCondition:'1',Search_Sdate:'2026-10-01',Search_Edate:'2026-10-01',Currency:'JPY'};expect(await api.execute(config(),'ShippingBasic.GetSellingReportDetailList',p)).toEqual({data:xml,media_type:'text/xml'});expect(new URLSearchParams(fetch.mock.calls[0][1].body).get('returnType')).toBe('xml');for(let i=0;i<3;i++)await expect(api.execute(config(),'ShippingBasic.GetSellingReportDetailList',p)).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
 });
 it('rejects incomplete, foreign and imprecise results without silently clipping or substituting business data',async()=>{
  const fetch=vi.fn().mockResolvedValueOnce(reply({Items:[]})).mockResolvedValueOnce(reply([{ItemCode:'9999999999'}])).mockResolvedValueOnce(new Response('{"ResultCode":0,"ResultObject":{"GdNo":"1234567890","BIContentsNo":9.223372036854775807e18}}')).mockResolvedValueOnce(reply({}));vi.stubGlobal('fetch',fetch);
  await expect(api.execute(config(),'ItemsLookup.GetAllGoodsInfo',{ItemStatus:'S2'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});await expect(api.execute(config(),'ItemsLookup.GetItemDetailInfo',{ItemCode:'1234567890'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});await expect(api.execute(config(),'ItemsBasic.SetNewGoods',{SecondSubCat:'300000001',ItemTitle:'Linen',ItemPrice:1000,ItemQty:1,AvailableDateType:'0',AvailableDateValue:'3'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});await expect(api.execute(config(),'CSCenter.SetInquiryMessage',{inq_type:'MSG',question_no:'1',seq_no:'1',contents:'Reply'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
 });
 it('blocks credential substitution, malformed dates, raw JSON escapes and excess batch work before network access',async()=>{
  const fetch=vi.fn();vi.stubGlobal('fetch',fetch);for(const [name,p]of [['ShippingBasic.GetShippingInfo_v3',{SearchStartDate:'20260230'}],['ItemsLookup.GetAllGoodsInfo',{ItemStatus:'S9'}],['CommonInfoLookup.SearchBrand',{keyword:'Linen',GiosisCertificationKey:KEY}],['ItemsOrder.SetGoodsPriceQtyBulk',{ItemInfoJson:'[{"ItemCode":"1"}]'}],['ShippingBasic.SetSendingInfoBulk',{ShippingInfoJson:Array.from({length:11},(_,i)=>({OrderNo:String(i),ShippingCorp:'A',TrackingNo:'A'}))}],['ItemsOptions.EditGoodsInventory',{ItemCode:'1234567890',InventoryInfo:Array.from({length:11},()=> '色||*青||*0||*1||*BLUE').join('$$')}],['ItemsContents.EditGoodsContents',{ItemCode:'1234567890',Contents:'a'.repeat(256*1024)}]])await expect(api.execute(config(),name,p)).rejects.toMatchObject({code:'E_BAD_INPUT'});
  const c=config();c.credentials.certification_key='different-key';await expect(api.execute(c,'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).rejects.toMatchObject({code:'E_TOOL_CALL_AUTH'});expect(fetch).not.toHaveBeenCalled();
 });
 it('preserves error classification, cancellation and no-retry behavior without exposing credentials or provider errors',async()=>{
  for(const [status,code]of [[401,'E_TOOL_CALL_AUTH'],[403,'E_TOOL_CALL_AUTH'],[429,'E_TOOL_CALL_RATE_LIMIT'],[503,'E_TOOL_CALL_UPSTREAM']] as const){const fetch=vi.fn().mockResolvedValue(new Response(KEY,{status}));vi.stubGlobal('fetch',fetch);await expect(api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).rejects.toMatchObject({code,message:expect.not.stringContaining(KEY)});expect(fetch).toHaveBeenCalledOnce();}
  const fetch=vi.fn().mockResolvedValueOnce(reply(undefined,-90004)).mockResolvedValueOnce(reply(undefined,-90001)).mockRejectedValueOnce(new DOMException(KEY,'TimeoutError')).mockResolvedValueOnce(reply([{M_B_NO:'1',M_B_NM:KEY,authorization:KEY}])).mockResolvedValueOnce(reply([{M_B_NM:'a'.repeat(1024*1024)}]));vi.stubGlobal('fetch',fetch);
  for(const code of ['E_TOOL_CALL_AUTH','E_TOOL_CALL_UPSTREAM','E_TOOL_CALL_TIMEOUT'])await expect(api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).rejects.toMatchObject({code});expect((await api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).data.ResultObject).toEqual([{M_B_NO:'1',M_B_NM:'[redacted]'}]);await expect(api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
  const controller=new AbortController();controller.abort();await expect(withRequestSignal(controller.signal,()=>api.execute(config(),'CommonInfoLookup.SearchBrand',{keyword:'Linen'}))).rejects.toMatchObject({code:'E_TOOL_CALL_CANCELLED'});expect(fetch).toHaveBeenCalledTimes(5);
 });
});
