import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {afterEach,expect,it,vi} from 'vitest';
const require=createRequire(import.meta.url),api=require('../../../../bin/shopee-business-api.cjs'),codec=require('../../../../bin/local-api-credential-codec.cjs'),contracts=require('../../../../bin/shopee-api-contracts.cjs').methods;
const {withRequestSignal}=require('../../../../bin/commerce-request-context.cjs');
const dirs:string[]=[];
function config(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orkas-shopee-native-'));dirs.push(dir);const credentialFile=path.join(dir,'grant'),credentialKey=crypto.randomBytes(32).toString('base64url'),metadata={shop_id:'456',region:'global',environment:'live'},credentials={provider:'shopee',partner_id:'12345',partner_key:'partner-test-secret',access_token:'access-test',refresh_token:'refresh-test',expires_at:Date.now()+3600000,refresh_expires_at:Date.now()+86400000,identity:{binding_shop_id:'456',region:'global',environment:'live'}};codec.writeCredentialFile(credentialFile,credentialKey,credentials);return {provider:'shopee',metadata,credentials,credentialFile,credentialKey};}
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status});
afterEach(()=>{vi.unstubAllGlobals();vi.restoreAllMocks();while(dirs.length)fs.rmSync(dirs.pop()!,{recursive:true,force:true});});
it('pins official shop identity and all nested fields while excluding credentials, binary and app-wide scope',()=>{
 expect(Object.keys(api.actionsFor())).toHaveLength(300);expect(api.actionsFor()['v2.product.add_item'].input_schema.properties.tax_info.properties.group_item_info.properties.group_qtd.type).toBe('string');
 for(const name of ['v2.product.batch_update_outlet_stock','v2.product.publish_item_to_outlet_shop','v2.public.get_access_token','v2.push.set_app_push_config','v2.public.get_shops_by_partner','v2.returns.convert_image','v2.ams.get_open_campaign_added_product','v2.global_product.add_global_item'])expect(api.isNative(name)).toBe(false);
 expect(api.actionsFor()['v2.product.get_weight_recommendation'].risk).toBe('R');expect(api.actionsFor()['v2.payment.generate_income_report'].risk).toBe('W');expect(api.actionsFor()['v2.ads.edit_auto_product_ads'].risk).toBe('D');
 expect(api.actionsFor()['v2.product.get_item_list_by_content_diagnosis'].input_schema.properties.page_size.maximum).toBe(48);expect(api.actionsFor()['v2.product.get_size_chart_list'].input_schema.properties.page_size['x-pageMax']).toBe(50);
 const {AjvJsonSchemaValidator}=require('@modelcontextprotocol/sdk/validation/ajv'),validator=new AjvJsonSchemaValidator();for(const r of Object.values(contracts) as any[])expect(()=>validator.getValidator(r.input_schema)).not.toThrow();
});
it('signs exact numeric request IDs using the existing owner, preserving full merchant response and extras',async()=>{
 const c=config(),calls:any[]=[];vi.stubGlobal('fetch',vi.fn(async(raw,init)=>{calls.push([raw,init]);return new Response('{"error":"","response":{"item_id":9007199254740993,"original_price":9007199254740992,"extra_id":18446744073709551615,"recipient_address":{"name":"Buyer","phone":"0123","full_address":"Dock"},"access_token":"access-test","memo":"access-test"}}');}));
 const result=await api.execute(c,'v2.product.update_item',{item_id:'9007199254740993',item_name:'Linen',image:{image_id_list:['image-1']}});const [raw,init]=calls[0],u=new URL(raw);expect(init.body).toContain('"item_id":9007199254740993');expect(u.origin).toBe('https://partner.shopeemobile.com');expect(u.searchParams.get('shop_id')).toBe('456');expect(u.searchParams.get('access_token')).toBe('access-test');const signature=crypto.createHmac('sha256','partner-test-secret').update('12345/api/v2/product/update_item'+u.searchParams.get('timestamp')+'access-test456').digest('hex');expect(u.searchParams.get('sign')).toBe(signature);expect(result.data.response.item_id).toBe('9007199254740993');expect(result.data.response.extra_id).toBe('18446744073709551615');expect(result.data.response.recipient_address.full_address).toBe('Dock');expect(JSON.stringify(result)).not.toContain('access-test');
});
it('rejects unknown, malformed, oversized and duplicate writes before refresh or business I/O',async()=>{
 const c=config(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);
 for(const p of [{item_id:'9223372036854775808',price_list:[{model_id:0,original_price:1}]},{item_id:1,price_list:[{model_id:0,original_price:1,partner_key:'override'}]},{item_id:1,price_list:Array.from({length:11},(_,i)=>({model_id:i,original_price:1}))},{item_id:1,price_list:[{model_id:0,original_price:1},{model_id:0,original_price:2}]}])await expect(api.execute(c,'v2.product.update_price',p)).rejects.toMatchObject({code:'E_BAD_INPUT'});
 await expect(api.execute(c,'v2.product.update_item',{item_id:1,description:'a'.repeat(256*1024)})).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(c,'v2.product.get_size_chart_list',{category_id:'1',page_size:'51'})).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(fetch).not.toHaveBeenCalled();
});
it('retains pagination and full order optional fields without auto-following URLs',async()=>{
 const c=config();const fetch=vi.fn(async()=>response({error:'',response:{order_list:[{order_sn:'A',recipient_address:{name:'Buyer',phone:'0123',full_address:'Dock'},item_list:[{item_id:123,item_name:'Linen'}]}]}}));vi.stubGlobal('fetch',fetch);
 const result=await api.execute(c,'v2.order.get_order_detail',{order_sn_list:'A',response_optional_fields:'recipient_address,item_list,invoice_data,international_label'});expect(result.data.response.order_list[0].recipient_address.full_address).toBe('Dock');expect(new URL(fetch.mock.calls[0][0]).searchParams.get('response_optional_fields')).toBe('recipient_address,item_list,invoice_data,international_label');expect(fetch).toHaveBeenCalledTimes(1);
});
it('correlates independent model and package acknowledgements and reports partial results without retry',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:{success_list:[{model_id:1,original_price:2}],failure_list:[{model_id:2,failed_reason:'Insufficient permission'}]}}));vi.stubGlobal('fetch',fetch);const p={item_id:123,price_list:[{model_id:1,original_price:2},{model_id:2,original_price:3}]};expect((await api.execute(c,'v2.product.update_price',p)).status).toBe('partial_or_failed');
 fetch.mockImplementation(async()=>response({error:'',response:{success_list:[{model_id:1}],failure_list:[]}}));await expect(api.execute(c,'v2.product.update_price',p)).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
 fetch.mockImplementation(async()=>response({error:'',success_list:[{package_number:'P2'}],fail_list:[{package_number:'P1',fail_reason:'Locked'}]}));expect((await api.execute(c,'v2.logistics.mass_ship_order',{package_list:[{package_number:'P1'},{package_number:'P2'}],pickup:{address_id:2,pickup_time_id:'T'}})).status).toBe('partial_or_failed');expect(fetch).toHaveBeenCalledTimes(3);
});
it('keeps async submission separate from ongoing and completed task outcomes',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:{task_id:123}}));vi.stubGlobal('fetch',fetch);expect((await api.execute(c,'v2.product.batch_add_item',{item_list:[{original_price:2,description:'Linen',weight:0.2,item_name:'Linen',logistic_info:[{logistic_id:1,enabled:true}],category_id:1,image:{image_id_list:['img1']}}]})).status).toBe('accepted');
 fetch.mockImplementation(async()=>response({error:'',response:{publish_status:1,success_list:[],failed_list:[]}}));expect((await api.execute(c,'v2.product.get_batch_task_result',{task_type:2,task_id:123})).status).toBe('accepted');fetch.mockImplementation(async()=>response({error:'',response:{publish_status:2,success_list:[{shop_id:456,item_id:1,model_id:0}],failed_list:[]}}));expect((await api.execute(c,'v2.product.get_batch_task_result',{task_type:2,task_id:123})).status).toBe('acknowledged');
 fetch.mockImplementation(async()=>response({error:'',response:{publish_status:2,success_list:[],failed_list:[{shop_id:456,item_id:1,model_id:0}]}}));expect((await api.execute(c,'v2.product.get_batch_task_result',{task_type:2,task_id:123})).status).toBe('partial_or_failed');
});
it('rejects metadata-only acknowledgements, unsafe exponential IDs, deep and oversized responses',async()=>{
 const c=config(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);for(const text of ['{"error":"","request_id":"r"}','{"error":"","response":{}}','{"error":"","response":{"item_id":9.007199254740993e15}}','{"error":"","response":{"item_id":1,"unknown":9.007199254740993e15}}','{"error":"","response":{"item_id":1,"nested":'+ '['.repeat(41)+'0'+']'.repeat(41)+'}}','{"error":"","response":{"item_id":1,"long":"'+'x'.repeat(1024*1024)+'"}}']){fetch.mockImplementation(async()=>new Response(text));await expect(api.execute(c,'v2.product.update_item',{item_id:1,item_name:'Test'})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});}
});
it('preserves closed timeout, cancellation, rate limit, auth and transport errors without replay',async()=>{
 const c=config(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);for(const [fault,code]of [[new Response('{}',{status:401}),'E_TOOL_CALL_AUTH'],[new Response('{}',{status:429}),'E_TOOL_CALL_RATE_LIMIT'],[new Response('{}',{status:503}),'E_TOOL_CALL_UPSTREAM'],[new TypeError('private-token'),'E_TOOL_CALL_NETWORK'],[new DOMException('private-token','TimeoutError'),'E_TOOL_CALL_TIMEOUT']] as const){fetch.mockImplementation(async()=>{if(fault instanceof Error)throw fault;return fault;});await expect(api.execute(c,'v2.order.set_note',{order_sn:'A',note:'Packed'})).rejects.toMatchObject({code});}const abort=new AbortController();abort.abort();await expect(withRequestSignal(abort.signal,()=>api.execute(c,'v2.order.set_note',{order_sn:'A',note:'Packed'}))).rejects.toMatchObject({code:'E_TOOL_CALL_CANCELLED'});expect(fetch).toHaveBeenCalledTimes(5);
});
it('shares owner refresh and persists the rotated credentials before a failed write',async()=>{
 const c=config();c.credentials.expires_at=0;codec.writeCredentialFile(c.credentialFile,c.credentialKey,c.credentials);const fetch=vi.fn(async(raw:string)=>{if(new URL(raw).pathname==='/api/v2/auth/access_token/get')return response({error:'',access_token:'new-access',refresh_token:'new-refresh',expire_in:3600,shop_id:456});expect(codec.readCredentialFile(c.credentialFile,c.credentialKey).refresh_token).toBe('new-refresh');return response({},503);});vi.stubGlobal('fetch',fetch);const results=await Promise.allSettled([api.execute(c,'v2.order.set_note',{order_sn:'A',note:'Packed'}),api.execute({...c},'v2.shop.get_profile',{})]);expect(results.every(x=>x.status==='rejected')).toBe(true);expect(fetch.mock.calls.filter(([raw])=>raw.includes('/auth/'))).toHaveLength(1);expect(fetch).toHaveBeenCalledTimes(3);
});
it('uses public signatures only where the official operation requires them and preserves shop binding',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:[]}));vi.stubGlobal('fetch',fetch);await api.execute(c,'v2.payment.get_payment_method_list',{});const u=new URL(fetch.mock.calls[0][0]);expect(u.searchParams.has('access_token')).toBe(false);expect(u.searchParams.has('shop_id')).toBe(false);expect(u.searchParams.get('sign')).toBe(crypto.createHmac('sha256','partner-test-secret').update('12345/api/v2/payment/get_payment_method_list'+u.searchParams.get('timestamp')).digest('hex'));c.metadata.shop_id='789';await expect(api.execute(c,'v2.payment.get_payment_method_list',{})).rejects.toThrow();expect(fetch).toHaveBeenCalledTimes(1);
});
it('accepts official envelopes without generic error and nullable shop membership',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({shop_name:'Fixture',region:'SG',merchant_id:null}));vi.stubGlobal('fetch',fetch);expect((await api.execute(c,'v2.shop.get_shop_info',{})).data.merchant_id).toBeNull();
 fetch.mockImplementation(async()=>response({code:0,msg:'ok',result:[{order_type:'placed',performance:[{item_id:123,sales:9007199254740992}]}]}));expect((await api.execute(c,'v2.business_insights.get_marketing_hot_listing',{start_time:1,end_time:2,period:'1d'})).data.result[0].performance[0].sales).toBe(9007199254740992);
});
it('rejects duplicate model receipts and removes official diagnostics while retaining buyer business text',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:{success_list:[{model_id:1},{model_id:1}],failure_list:[]}}));vi.stubGlobal('fetch',fetch);await expect(api.execute(c,'v2.product.update_price',{item_id:1,price_list:[{model_id:1,original_price:2}]})).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
 fetch.mockImplementation(async()=>response({error:'',message:'private-diagnostic',response:{result_list:[{comment_id:1,fail_error:'item.error',fail_message:'private-diagnostic'}],buyer_message:'Please leave at reception'}}));const out=await api.execute(c,'v2.product.reply_comment',{comment_list:[{comment_id:1,comment:'Thank you'}]});expect(out.status).toBe('partial_or_failed');expect(JSON.stringify(out)).not.toContain('private-diagnostic');expect(out.data.response.buyer_message).toBe('Please leave at reception');
});
it('enforces official limits for union integer fields and arrays before I/O',async()=>{
 const c=config(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(api.execute(c,'v2.add_on_deal.get_add_on_deal_list',{page_no:'1001',page_size:10})).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(c,'v2.product.get_item_base_info',{item_id_list:Array.from({length:51},(_,i)=>i+1)})).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(c,'v2.order.get_order_detail',{order_sn_list:Array.from({length:51},(_,i)=>'O'+i).join(',')})).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(fetch).not.toHaveBeenCalled();
});
it('recognizes official async terminal failures and preserves real floating point fields',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:{status:'FAILED',message:'private-provider-diagnostic'}}));vi.stubGlobal('fetch',fetch);const out=await api.execute(c,'v2.media_space.get_video_upload_result',{video_upload_id:'video1'});expect(out.status).toBe('partial_or_failed');expect(JSON.stringify(out)).not.toContain('private-provider-diagnostic');fetch.mockImplementation(async()=>response({error:'',response:{success_list:[{model_id:1,original_price:9007199254740992}],failure_list:[]}}));expect((await api.execute(c,'v2.product.update_price',{item_id:123,price_list:[{model_id:1,original_price:9007199254740992}]})).data.response.success_list[0].original_price).toBe(9007199254740992);
});
it('requires every stock location without rejecting distinct locations of one model',async()=>{
 const c=config(),fetch=vi.fn(async()=>response({error:'',response:{success_list:[{model_id:1,location_id:'A',stock:2},{model_id:1,location_id:'B',stock:3}],failure_list:[]}}));vi.stubGlobal('fetch',fetch);const p={item_id:123,stock_list:[{model_id:1,seller_stock:[{location_id:'A',stock:2},{location_id:'B',stock:3}]}]};expect((await api.execute(c,'v2.product.update_stock',p)).status).toBe('accepted');fetch.mockImplementation(async()=>response({error:'',response:{success_list:[{model_id:1,location_id:'A',stock:2}],failure_list:[]}}));await expect(api.execute(c,'v2.product.update_stock',p)).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
});

it('excludes arbitrary Outlet shop routing before all I/O',async()=>{const c=config(),fetch=vi.fn();vi.stubGlobal('fetch',fetch);await expect(api.execute(c,'v2.product.batch_update_outlet_stock',{item_list:[{outlet_shop_id:789,item_id:123,stock_list:[{model_id:0,seller_stock:[{stock:1}]}]}]})).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(fetch).not.toHaveBeenCalled();});
