import {createRequire} from 'node:module';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {expect,it} from 'vitest';
const require=createRequire(import.meta.url),codec=require('../../../../bin/local-api-credential-codec.cjs');
it('runs the encrypted Shop OAuth merchant journey over six MCP tools with restart and R/W/H/D boundaries',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'orkas-shopee-journey-')),file=path.join(dir,'grant.enc'),key=crypto.randomBytes(32).toString('base64url'),preload=path.join(dir,'provider.cjs'),journal=path.join(dir,'wire.jsonl');
 const metadata={shop_id:'456',region:'global',environment:'live'},grant={provider:'shopee',partner_id:'12345',partner_key:'fixture-partner-private',access_token:'fixture-access-private',refresh_token:'fixture-refresh-private',expires_at:Date.now()+3600000,refresh_expires_at:Date.now()+86400000,identity:{binding_shop_id:'456',region:'global',environment:'live'}};codec.writeCredentialFile(file,key,grant);
 fs.writeFileSync(preload,`
 const fs=require('node:fs'),crypto=require('node:crypto');global.fetch=async(raw,init)=>{const u=new URL(raw),params=init.body?JSON.parse(init.body):Object.fromEntries(u.searchParams);if(u.origin!=='https://partner.shopeemobile.com'||u.searchParams.get('shop_id')!=='456'||u.searchParams.get('access_token')!=='fixture-access-private')throw Error('Unbound request');const signature=crypto.createHmac('sha256','fixture-partner-private').update('12345'+u.pathname+u.searchParams.get('timestamp')+'fixture-access-private456').digest('hex');if(u.searchParams.get('sign')!==signature)throw Error('Incorrect signature');fs.appendFileSync(process.env.FIXTURE_JOURNAL,JSON.stringify({route:u.pathname,params})+'\\n');const reply=response=>new Response(JSON.stringify({error:'',request_id:'R',response}));
 if(u.pathname==='/api/v2/shop/get_shop_info')return new Response(JSON.stringify({shop_id:456,shop_name:'Fixture',region:'SG',merchant_id:null,error:''}));
 if(u.pathname==='/api/v2/order/get_order_detail'){if(params.response_optional_fields!=='recipient_address,item_list')throw Error('Lost order fields');return reply({order_list:[{order_sn:'A',recipient_address:{name:'Buyer',phone:'0123',full_address:'Dock'},item_list:[{item_id:123,item_name:'Linen'}]}]});}
 if(u.pathname==='/api/v2/order/set_note'){if(params.note!=='Packed')throw Error('Lost note');return reply();}
 if(u.pathname==='/api/v2/product/update_item'){if(params.item_name!=='Linen')throw Error('Lost product field');return reply({item_id:123,item_name:'Linen'});}
 if(u.pathname==='/api/v2/product/update_price')return reply({success_list:[{model_id:1,original_price:2}],failure_list:[{model_id:2,failed_reason:'private-failure-text'}]});
 if(u.pathname==='/api/v2/order/cancel_order')return reply({update_time:1790800000});throw Error('Unexpected request');};`);
 const clients:Client[]=[],stderr:string[]=[];async function connect(){const client=new Client({name:'shopee-merchant-journey',version:'1'});clients.push(client);const transport=new StdioClientTransport({command:process.execPath,args:['--require',preload,path.resolve(__dirname,'../../../../bin/direct-commerce-mcp-server.cjs')],stderr:'pipe',env:{...Object.fromEntries(Object.entries(process.env).filter((x):x is [string,string]=>typeof x[1]==='string')),ELECTRON_RUN_AS_NODE:'1',ORKAS_LOCAL_API_PROVIDER:'shopee',ORKAS_LOCAL_API_CREDENTIAL_FILE:file,ORKAS_LOCAL_API_CREDENTIAL_KEY:key,ORKAS_LOCAL_API_METADATA_JSON:JSON.stringify(metadata),FIXTURE_JOURNAL:journal}});transport.stderr?.on('data',data=>stderr.push(String(data)));await client.connect(transport);return client;}
 const read=(r:any)=>JSON.parse(r.content[0].text);
 try{const client=await connect();expect((await client.listTools()).tools).toHaveLength(6);const directory=read(await client.callTool({name:'list_capabilities',arguments:{}}));expect(directory.actions).toHaveLength(309);expect(JSON.stringify(directory)).not.toContain('input_schema');const described=read(await client.callTool({name:'describe_action',arguments:{action:'v2.product.update_item'}}));expect(described.input_schema.properties.tax_info.properties.group_item_info.properties.group_qtd.type).toBe('string');
 const order=await client.callTool({name:'execute_read',arguments:{action:'v2.order.get_order_detail',parameters:{order_sn_list:'A',response_optional_fields:'recipient_address,item_list'}}});expect(order.isError).not.toBe(true);expect(read(order).result.data.response.order_list[0].recipient_address.full_address).toBe('Dock');
 const note={action:'v2.order.set_note',parameters:{order_sn:'A',note:'Packed'}};expect((await client.callTool({name:'execute_read',arguments:note})).isError).toBe(true);expect((await client.callTool({name:'execute_write',arguments:note})).isError).not.toBe(true);
 const edit={action:'v2.product.update_item',parameters:{item_id:123,item_name:'Linen'}};expect((await client.callTool({name:'execute_write',arguments:edit})).isError).toBe(true);expect((await client.callTool({name:'execute_high_impact',arguments:edit})).isError).not.toBe(true);await client.close();const restarted=await connect();
 const partial=await restarted.callTool({name:'execute_high_impact',arguments:{action:'v2.product.update_price',parameters:{item_id:123,price_list:[{model_id:1,original_price:2},{model_id:2,original_price:3}]}}});expect(partial.isError).toBe(true);expect(read(partial).result.status).toBe('partial_or_failed');expect(JSON.stringify(partial)).not.toContain('private-failure-text');
 const cancel={action:'v2.order.cancel_order',parameters:{order_sn:'A',cancel_reason:'OUT_OF_STOCK',item_list:[{item_id:123,model_id:1}]}};expect((await restarted.callTool({name:'execute_high_impact',arguments:cancel})).isError).toBe(true);expect((await restarted.callTool({name:'execute_destructive',arguments:cancel})).isError).not.toBe(true);
 expect(fs.readFileSync(journal,'utf8').trim().split('\n').map(line=>JSON.parse(line).route)).toEqual(['/api/v2/shop/get_shop_info','/api/v2/shop/get_shop_info','/api/v2/order/get_order_detail','/api/v2/order/set_note','/api/v2/product/update_item','/api/v2/product/update_price','/api/v2/order/cancel_order']);expect(codec.readCredentialFile(file,key)).toEqual(grant);expect(stderr).toEqual([]);expect(JSON.stringify([order,partial])).not.toContain('fixture-access-private');
 }finally{await Promise.allSettled(clients.map(c=>c.close()));fs.rmSync(dir,{recursive:true,force:true});}
},20000);
