import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import {expect,it,vi} from 'vitest';
const require=createRequire(import.meta.url),api=require('../../../../bin/taobao-business-api.cjs'),contracts=require('../../../../bin/taobao-api-contracts.cjs');
const evidence=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../../../fixtures/connectors/official-contracts/taobao-20261001.json'),'utf8'));
const config=(type?:string)=>({provider:'taobao_top',metadata:{},credentials:{app_key:'fixture-app',app_secret:'fixture-secret',access_token:'fixture-access',identity:{user_id:'123',nick:'fixture-shop',...(type?{seller_type:type}:{})}}});
const owner=(reply:unknown)=>({request:vi.fn(async()=>reply)});
it('exposes only the current seller product and keeps field discovery bounded to one action',()=>{
 const b=api.actionsFor(config('B')),c=api.actionsFor(config('C')),unknown=api.actionsFor(config());expect(Object.keys(b)).toHaveLength(389);expect(c).toEqual(unknown);expect(b).toHaveProperty('tmall.item.quantity.update');expect(c).not.toHaveProperty('tmall.item.quantity.update');expect(b).not.toHaveProperty('taobao.user.buyer.get');expect(b).not.toHaveProperty('taobao.rp.refunds.agree');expect(b).not.toHaveProperty('taobao.item.img.upload');expect(b['taobao.trade.fullinfo.get'].input_schema.properties).toHaveProperty('tid');expect(b['taobao.items.onsale.get'].requirements.billing.provider_billed).toBe(true);
});
it('compiles each current official full input tree and excludes public signing controls',()=>{
 const ajv=new(require('@modelcontextprotocol/sdk/validation/ajv').AjvJsonSchemaValidator)();for(const row of Object.values(contracts.methods) as any[]){expect(()=>ajv.getValidator(row.input_schema)).not.toThrow();for(const name of ['method','session','app_key','sign','url'])expect(row.input_schema.properties).not.toHaveProperty(name);expect(row.input_schema.additionalProperties).toBe(false);}
});
it('uses independent frozen official responses and retains the documented sample defects separately',()=>{
 let valid=0,invalidJson=0,invalidShape=0;for(const r of evidence.normalized_contracts){try{JSON.parse(r.official_response_example);}catch{invalidJson++;continue;}if(r.method==='tmall.product.template.get'){expect(()=>api.validateResponseShape(r.method,r.official_response_example)).toThrow(/invalid type/);invalidShape++;continue;}expect(()=>api.validateResponseShape(r.method,r.official_response_example)).not.toThrow();valid++;}expect({valid,invalidJson,invalidShape}).toEqual({valid:380,invalidJson:8,invalidShape:1});
});
it('preserves full order fulfilment contacts, business notes and exact IDs',async()=>{
 const reply=api.parse('{"trade_fullinfo_get_response":{"trade":{"tid":9007199254740993,"receiver_name":"Fixture buyer","receiver_mobile":"13800138000","receiver_address":"Fixture road","seller_memo":"Keep the business note","orders":[{"oid":9007199254740994,"item_memo":"fragile"}]},"access_token":"fixture-access","request_id":"provider trace"}}');const o=owner(reply);const r=await api.execute(config(),'taobao.trade.fullinfo.get',{tid:'9007199254740993',fields:'receiver_name,receiver_mobile,receiver_address,seller_memo,orders'},o);expect(o.request.mock.calls[0][2].fields).toContain('tid');expect(r.data.trade_fullinfo_get_response.trade).toMatchObject({tid:'9007199254740993',receiver_name:'Fixture buyer',receiver_mobile:'13800138000',seller_memo:'Keep the business note',orders:[{oid:'9007199254740994',item_memo:'fragile'}]});expect(JSON.stringify(r)).not.toContain('fixture-access');expect(JSON.stringify(r)).not.toContain('provider trace');expect(()=>api.parse('{"id":9.007199254740993e15}')).toThrow(/imprecise/);
});
it('rejects a wrong seller, unknown fields and malformed numbers before any business IO',async()=>{
 const o=owner({});await expect(api.execute(config(),'taobao.sellercenter.roles.get',{nick:'other-shop'},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(config(),'taobao.item.delete',{num_iid:9007199254740992},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(config(),'taobao.item.delete',{num_iid:'0001'},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});await expect(api.execute(config(),'taobao.item.delete',{num_iid:'123',session:'injected'},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(o.request).not.toHaveBeenCalled();
});
it('honours the official page maximum when it is below the host limit',async()=>{
 const o=owner({});await expect(api.execute(config(),'taobao.trades.sold.history.get',{fields:'tid',page_size:51},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(o.request).not.toHaveBeenCalled();expect(contracts.methods['taobao.trades.sold.history.get'].input_schema.properties.page_size['x-max']).toBe('50');
});
it('keeps DTO keys literal and exact numbers numeric on the signed form wire',async()=>{
 const o=owner({tmall_item_quantity_update_response:{quantity_update_result:'9007199254740993'}});await api.execute(config('B'),'tmall.item.quantity.update',{item_id:'9007199254740993',sku_quantities:[{sku_id:'9007199254740994',quantity:0}],options:{type:1}},o);expect(o.request.mock.calls[0][2]).toMatchObject({item_id:'9007199254740993',sku_quantities:'[{"sku_id":9007199254740994,"quantity":0}]',options:'{"type":1}'});await expect(api.execute(config(),'tmall.item.quantity.update',{item_id:'1',item_quantity:1},o)).rejects.toMatchObject({code:'E_TOOL_CALL_AUTH'});expect(o.request).toHaveBeenCalledOnce();
});
it('rejects incomplete absolute stock receipts and never retries incremental changes',async()=>{
 const p={num_iid:'1234',sku_id:'9',quantity:0,type:1};for(const item of [{num_iid:1234},{num_iid:1234,skus:[{sku_id:9,quantity:1}]},{num_iid:999,skus:[{sku_id:9,quantity:0}]}]){const o=owner({item_quantity_update_response:{item}});await expect(api.execute(config(),'taobao.item.quantity.update',p,o)).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});expect(o.request).toHaveBeenCalledOnce();}const o=owner({item_quantity_update_response:{item:{num_iid:1234,skus:[{sku_id:9,quantity:7}]}}});const r=await api.execute(config(),'taobao.item.quantity.update',{...p,quantity:-1,type:2},o);expect(r.status).toBe('accepted');expect(r.follow_up).toMatch(/not automatically replay/);expect(o.request).toHaveBeenCalledOnce();
});
it('bounds legacy string-shaped SKU batches and correlates each returned absolute quantity',async()=>{
 const p={num_iid:'1234',skuid_quantities:'9:0;10:2',type:1},o=owner({item:0});await expect(api.execute(config(),'taobao.skus.quantity.update',{...p,skuid_quantities:Array.from({length:11},(_,i)=>`${i+1}:0`).join(';')},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(o.request).not.toHaveBeenCalled();for(const skus of [[{sku_id:9,quantity:0}],[{sku_id:9,quantity:0},{sku_id:9,quantity:0}],[{sku_id:9,quantity:0},{sku_id:10,quantity:3}]])await expect(api.execute(config(),'taobao.skus.quantity.update',p,owner({skus_quantity_update_response:{item:{num_iid:1234,skus}}}))).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});expect((await api.execute(config(),'taobao.skus.quantity.update',p,owner({skus_quantity_update_response:{item:{num_iid:1234,skus:[{sku_id:10,quantity:2},{sku_id:9,quantity:0}]}}}))).status).toBe('accepted');
});
it('does not turn false cancellation receipts or empty gateway results into success',async()=>{
 const result=await api.execute(config(),'cainiao.waybill.ii.cancel',{cp_code:'ZTO',waybill_code:'WB1'},owner({cainiao_waybill_ii_cancel_response:{cancel_result:false}}));expect(result.status).toBe('partial_or_failed');for(const body of [{},{items_onsale_get_response:{}},{item_delete_response:{request_id:'trace'}}])await expect(api.execute(config(),body.item_delete_response?'taobao.item.delete':'taobao.items.onsale.get',body.item_delete_response?{num_iid:'123'}:{fields:'num_iid'},owner(body))).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});const empty=await api.execute(config(),'taobao.items.onsale.get',{fields:'num_iid'},owner({items_onsale_get_response:{total_results:0}}));expect(empty.data.items_onsale_get_response.total_results).toBe(0);
});
it('requires attributed receipts for every delivery preference entry and preserves failed identities',async()=>{
 const p={mail_order_delivery_preference_top_request_dto:{request_id:'request-1',mail_order_delivery_preference_d_t_o_list:[{unique_key:'a',mail_order_id:'WB1',cp_code:'ZTO',logistics_node:'delivery',preference_source:'buyer'},{unique_key:'b',mail_order_id:'WB2',cp_code:'ZTO',logistics_node:'delivery',preference_source:'buyer'}]}},body={alibaba_logistics_mail_order_delivery_preference_add_response:{api_result:{success:true,message:'Private gateway prose',data:{success_mail_order_unique_key_list:['a'],failed_mail_order_unique_key_list:['b'],failed_mail_order_reason_map:'Private failed prose'}}}};const r=await api.execute(config(),'alibaba.logistics.mail.order.delivery.preference.add',p,owner(body));expect(r.status).toBe('partial_or_failed');expect(r.data.alibaba_logistics_mail_order_delivery_preference_add_response.api_result.data.failed_mail_order_unique_key_list).toEqual(['b']);expect(JSON.stringify(r)).not.toMatch(/Private/);body.alibaba_logistics_mail_order_delivery_preference_add_response.api_result.data.failed_mail_order_unique_key_list=[];await expect(api.execute(config(),'alibaba.logistics.mail.order.delivery.preference.add',p,owner(body))).rejects.toMatchObject({code:'E_TOOL_CALL_UPSTREAM'});
});
it('keeps closed permission, rate, network and cancellation failures without provider prose or replay',async()=>{
 for(const code of ['E_TOOL_CALL_AUTH','E_TOOL_CALL_RATE_LIMIT','E_TOOL_CALL_NETWORK','E_TOOL_CALL_TIMEOUT','E_TOOL_CALL_CANCELLED']){const o={request:vi.fn(async()=>{throw Object.assign(new Error('Private provider error'),{code});})};await expect(api.execute(config(),'taobao.item.delete',{num_iid:'123'},o)).rejects.toMatchObject({code});expect(o.request).toHaveBeenCalledOnce();try{await api.execute(config(),'taobao.item.delete',{num_iid:'123'},o);}catch(e){expect(String(e)).not.toContain('Private');}}
});
it('provides complete source-permitted alias selectors without requesting unsupported list fields',()=>{
 expect(api.fieldsFor('taobao.items.onsale.get').split(',')).toHaveLength(22);expect(api.fieldsFor('taobao.items.onsale.get')).not.toContain('skus');expect(api.fieldsFor('taobao.items.inventory.get').split(',')).toHaveLength(21);expect(api.fieldsFor('taobao.trades.sold.get')).toContain('receiver_address');expect(api.fieldsFor('taobao.trades.sold.get')).toContain('orders.oid');expect(api.fieldsFor('taobao.item.seller.get')).toContain('skus.sku_id');
});

it('blocks mixed SKU identity modes before an unpredictable provider update',async()=>{
 const o=owner({tmall_item_quantity_update_response:{quantity_update_result:'123'}});await expect(api.execute(config('B'),'tmall.item.quantity.update',{item_id:'123',sku_quantities:[{sku_id:'1',quantity:0},{outer_id:'external',quantity:0}]},o)).rejects.toMatchObject({code:'E_BAD_INPUT'});expect(o.request).not.toHaveBeenCalled();
});
